### ISSUE TITLE
Address broken in frontend

### ISSUE THREAD

**Issue by brancz** [parca-dev/parca#1018]
I'm pretty sure this happened in the protobuf-ts migration, but I'm having a difficult time fixing this as none of the addr2line tools appear to work correctly on OSX so I can't test whether what I'm doing is correct.

<img width="1512" alt="Screenshot 2022-05-05 at 18 54 38" src="https://user-images.githubusercontent.com/4546722/166973890-7fa8a62c-53ad-4051-997c-9c4fa8b33ae0.png">

**Comment by knrt10** [comment]
I would like to look into this, if no one is working.

**Comment by brancz** [comment]
I don’t think anyone is working on this, feel free to pick it up and let us know if any further context would be helpful!

**Comment by knrt10** [comment]
#929 looks like a good first issue to understand the codebase. If it's okay I would like to implement that first. Will work on this after. If someone else wants to take it up in the meantime, please feel free to do so.

**Comment by brancz** [comment]
Sounds good!
