### ISSUE TITLE
UI fails to load if start and end timestamps are not supplied

### ISSUE THREAD

**Issue by bill3tt** [parca-dev/parca#1056]
If you strip the `from_a` and `to_a` parameters from the query string, the UI fails to load.

I would exepect that, in the absence of these parameters, Parca would pick 'sensible' defaults such as from: now, to: now-3h.

![image](https://user-images.githubusercontent.com/33524269/168695534-57378ba0-fd23-49f7-9b63-5cbf0781ca03.png)

This is unfortunate because I wanted to demo how to hop between Prometheus exemplars and Parca in my Kubecon [demo](https://prometheusdayeu22.sched.com/event/zfKp?iframe=no), but that is on me for leaving this so late :(

**Comment by manojVivek** [comment]
No worries, thanks for opening the issue.
I'm working on it, should be available before your demo today.

**Comment by bill3tt** [comment]
Thanks for the fast turn around @manojVivek :muscle: I'll do my best to see if we can squeeze this into the demo.

**Comment by manojVivek** [comment]
Glad, we could make it on time. 
It deployed to demo.parca.dev as well. 👍🏼

**Comment by brancz** [comment]
🥳 closing, thanks @bill3tt for raising the issue and @manojVivek for fixing it so fast!
