### ISSUE TITLE
Replace graphviz dependency

### ISSUE THREAD

**Issue by brancz** [parca-dev/parca#109]
It would be nice if conprof didn't depend on graphviz.

Potential pure go candidate to replace it: https://github.com/wwmoraes/dot

**Comment by metalmatze** [comment]
As it turns out after trying to work with this libarary a bit more it's only for generating the `.dot` files. It doesn't help in any way generate a SVG from a dot file. 
I don't think this is the replacement we're looking for :confused:

**Comment by brancz** [comment]
Meh.

**Comment by bboreham** [comment]
I never look at the graphviz view since they added Flame Graph; if you defaulted conprof to showing that then it would be a user choice whether they want to pick the Graph view and hence need to install graphviz.

**Comment by brancz** [comment]
We just serve the standard pprof UI from the pprof toolchain... I suppose we can probably construct the URL in a way that opens the flamegraph by default? I think that shouldn't be too difficult. I also tend to browse to the flamegraph directly.

**Comment by brancz** [comment]
No graphviz present anymore :)
