### ISSUE TITLE
Parca server and agent helm charts

### ISSUE THREAD

**Issue by Pryz** [parca-dev/parca#1129]
Hi there,

Would be lovely to have some helm charts to deploy both the parca server and agent. I saw the jsonnet config but a lot of workflows are based on Helm so it might make sense to also provide some charts !

Thanks !

**Comment by brancz** [comment]
Actually, someone in the community already created them and we've been wanting to move them over to the parca org. Let me check with them again. (On discord the user's handle is `@lex` if I recall correctly)

**Comment by brancz** [comment]
Ah found it. @rlex I know we talked about this a while ago, would you be open to moving the helm charts to the parca org?

**Comment by rlex** [comment]
i just migrated my chart to parca org, tests are welcome https://github.com/parca-dev/helm-charts

**Comment by kakkoyun** [comment]
We have the repo now. So this is done.
