### ISSUE TITLE
chore: Use Renovate where Dependabot falls short

### ISSUE THREAD

**Issue by kakkoyun** [parca-dev/parca#1162]
Yes, I have checked the Renovate, and it has more features than the Dependabot. Especially it is useful for our use cases (pinned docker containers, etc). I don't mind using it, as long as it's free :D Would you be up for creating an equivalent configuration? (considering your experience with it) It would speed things up!

_Originally posted by @kakkoyun in https://github.com/parca-dev/parca/pull/1161#discussion_r899796933_

**Comment by maxbrunet** [comment]
Ok, it should be easy, please install the app on the repository/ies, it is safe to do so, it will open an onboarding PR and will not start updates until its config is in the main branch:

> Conveniently, Renovate will not make any changes to your repository or raise any further Pull Requests until after you merge the onboarding Pull Request.

Please see https://docs.renovatebot.com/getting-started/installing-onboarding/ for more details.

I'll make PRs to the onboarding branch until we are satisfied with the config.

**Comment by maxbrunet** [comment]
Done in #1163 #1214
