### ISSUE TITLE
Metrics graph refreshes if profile type changes

### ISSUE THREAD

**Issue by metalmatze** [parca-dev/parca#1179]
Right now, when clicking on a specific profile timestamp in the metrics graph the metrics also reload.
When changing the type from icicle graph to table the metrics graph also refreshes, although the timestamps don't change.

**Comment by monicawoj** [comment]
@metalmatze is this still reproducible? When I change from icicle graph to table and vice-versa I do not see the metrics graph refreshing. Maybe you can share a recording of what you mean if you still see the issue?

**Comment by metalmatze** [comment]
Checked with the latest `main` branch again. It's gone now. 
It probably was another symptom of the labels not being consistent and broken which was fixed with #1280.
