### ISSUE TITLE
Search state isn't reset when changing profile (type, timestamp)

### ISSUE THREAD

**Issue by metalmatze** [parca-dev/parca#1181]
When searching for a stack trace in one profile and then changing the profile's time or even the type entirely the search state stays the same. While I can see that making sense for the exact same profile series (so labels not changing between queries) it doesn't make sense if looking at entirely new profiles.

**Comment by brancz** [comment]
just to make sure I understand this right, you expected labels to be cleared, when you select a different profile type?
