### ISSUE TITLE
scrape: Sample has no location ids

### ISSUE THREAD

**Issue by javierhonduco** [parca-dev/parca#1264]
Based off current `main` (`5277034f80d8f7310e4a0ec740f63b66459a2399`) and with the default config, I am seeing these errors that didn't appeared before:

```
level=error name=parca ts=2022-06-29T14:53:49.215847316Z caller=scrape.go:500 scrape_pool=default target=http://127.0.0.1:7070/debug/pprof/goroutine msg="WriteRaw failed for scraped profile" err="rpc error: code = Internal desc = failed to ingest profile: sample 44 has no location ids"
level=error name=parca ts=2022-06-29T14:53:55.215188678Z caller=scrape.go:500 scrape_pool=default target=http://127.0.0.1:7070/debug/pprof/goroutine msg="WriteRaw failed for scraped profile" err="rpc error: code = Internal desc = failed to ingest profile: sample 44 has no location ids"
level=error name=parca ts=2022-06-29T14:53:58.215063347Z caller=scrape.go:500 scrape_pool=default target=http://127.0.0.1:7070/debug/pprof/goroutine msg="WriteRaw failed for scraped profile" err="rpc error: code = Internal desc = failed to ingest profile: sample 44 has no location ids"
```

**Comment by kakkoyun** [comment]
I've seen similar errors as well.

**Comment by brancz** [comment]
I think we should add the value of that sample to that error, because if the value is 0, then we can ignore this error. It appears to be coming from the goroutine profile, every go routine is started by some line of code so, it seems like this makes no sense semantically. Let's start with adding the sample value and see if that shines more light on this.

**Comment by maxbrunet** [comment]
I quickly looked into it a couple days ago, iirc the value was 1, I do not know enough yet to tell what it means

**Comment by brancz** [comment]
It seems that this is actually a valid thing, so we need to allow stack traces with no locations, we'll probably have to introduce a special case for this.

**Comment by brancz** [comment]
It basically means that the values are directly attributed to the root span (eg. the process). In this case it seems that the go routine does not attribute the `main` goroutine to anything other than the process, therefore no stack technically started it.
