### ISSUE TITLE
debuginfo/symbolizer: Decouple symbolization from debuginfo component

### ISSUE THREAD

**Issue by brancz** [parca-dev/parca#1273]
The debuginfo component is currently doing the actual symbolization, while the symbolizer really just handles the interaction with the metastore. This should be decoupled for a better separation of concerns.

I would propose to add download functionality to the debuginfo component, which the symbolized utilizes to get the debuginfos it cares about for a particular case of symbolizing.

**Comment by kakkoyun** [comment]
@brancz this has solved, no?

**Comment by brancz** [comment]
It has!
