### ISSUE TITLE
tags: keys and values seem to get mixed

### ISSUE THREAD

**Issue by javierhonduco** [parca-dev/parca#1281]
I am 99% sure I have made a silly mistake in my code, but while working on system-wide, I noticed that some tags keys and values are completely mixed! 

They are set in [here](https://github.com/parca-dev/parca-agent/pull/532/files#diff-3f678b06848d2ffbe8d609262ffa98b413fc99925cfdc9d8f40036d07be0aa37R588-R590) and added to the profile [over there](https://github.com/parca-dev/parca-agent/pull/532/files#diff-3f678b06848d2ffbe8d609262ffa98b413fc99925cfdc9d8f40036d07be0aa37R862-R868).

This is the issue as seen in the UI:

<img width="1059" alt="image" src="https://user-images.githubusercontent.com/959128/176724607-5ef8cea8-4fb9-4ece-906a-398a785ecef8.png">

(I am running current main of parca (`3dc62cfb7f2257a5c2c4d653c128d59e4196d69a`) and parca-agent rebased on the PR mentioned above, based off parca-agent's main, too (`aa9daea649e13c42c8b3d89bbe413588894ecd3a`))

It is odd because it seems random-ish! Sometimes it doesn't happen, and the wrong values appear in any of the 3 keys. Either way, just opening so I don't forget to follow up on this!

**Comment by brancz** [comment]
\* _hopes https://github.com/parca-dev/parca/pull/1280 fixed this_ *

**Comment by javierhonduco** [comment]
Closing as https://github.com/parca-dev/parca/pull/1280/files fixed this!! 🎉
