### ISSUE TITLE
ui: can't filter by a number of tags (OR over them)

### ISSUE THREAD

**Issue by javierhonduco** [parca-dev/parca#1283]
I can filter by this tag
<img width="1472" alt="image" src="https://user-images.githubusercontent.com/959128/176729305-d8c201d9-0d0a-42b9-9091-864f16355f30.png">

and by this one

<img width="1472" alt="image" src="https://user-images.githubusercontent.com/959128/176729346-23a34ebe-45d6-4998-9b25-8501fe25d27c.png">

but when I try to query for either profile:

<img width="999" alt="image" src="https://user-images.githubusercontent.com/959128/176729617-861d3b3e-8b58-499a-81f0-71579a85dbc0.png">

is it because it's doing a logic `AND` of the tags? In that case could it would be great to have a way to specify `AND` vs `OR` conditionals 😄

**Comment by maxbrunet** [comment]
> is it because it's doing a logic `AND` of the tags? In that case could it would be great to have a way to specify `AND` vs `OR` conditionals :smile:

With Prometheus, it is an `AND`, and a regex can be used instead, `cgroup_id~="42289|43099"`. Not sure if it supported by Parca, when I try to write the filter by hand with `~=` or `!=`, it disappears. It reappears if I select something from the autocomplete, but it is oddly concatenate

![image](https://user-images.githubusercontent.com/32458727/176749939-e3ca0a8c-4f96-4be7-bb2c-84fc00285766.png)

**Comment by brancz** [comment]
@maxbrunet is right, the way we do this is via the `~="a|b|c"` label matching.

**Comment by javierhonduco** [comment]
Closing this issue as the regex approach that Maxime suggested is the way to go :)
