### ISSUE TITLE
failed to decompress profile: gzip: invalid header

### ISSUE THREAD

**Issue by javierhonduco** [parca-dev/parca#1366]
After running Parca@https://github.com/parca-dev/parca/commit/ffa83684b5ea40cb3c30d672542e8d100e15f5ad for some minutes, this error message started showing up many times:

```level=error name=parca ts=2022-07-14T14:28:04.535566133Z caller=logger.go:35 protocol=grpc grpc.component=server grpc.service=parca.profilestore.v1alpha1.ProfileStoreService grpc.method=WriteRaw grpc.method_type=unary grpc.start_time=2022-07-14T15:28:04+01:00 grpc.code=Internal grpc.error="rpc error: code = Internal desc = failed to decompress profile: gzip: invalid header" grpc.time_ms=7.822 finishedcall=(MISSING)```

**Comment by brancz** [comment]
This is likely the agent sending a faulty profile, but in any case, Parca should not be returning an `Internal` error here, but rather `InvalidArgument`.

**Comment by heylongdacoder** [comment]
I think this already fixed by https://github.com/parca-dev/parca/pull/1396?

**Comment by kakkoyun** [comment]
> I think this already fixed by #1396?

It seems like it. Thanks.
