### ISSUE TITLE
UI: Selecting a different profile doesn't work as expected

### ISSUE THREAD

**Issue by lilic** [parca-dev/parca#1406]
To reproduce:
1. Select a point that opens in icicle view.
2. Now click down to a span in a graph.
3. Now click on a different point for a different process.
4. That results in seeing root 100% for example or other unexpected results.

I can provide a video of the screen if the above doesn't make sense.

**Comment by manojVivek** [comment]
Yes, I this is weird. I'll take a look. 👍🏼
