### ISSUE TITLE
Not clear how to build conprof tool and use it for profiling golang application

### ISSUE THREAD

**Issue by avinashk442** [parca-dev/parca#147]
Steps are not clear in readme how to build conprof tool and use it with any golang application. I will be very thankful if anyone can guide me. I followed whatever written in readme and getting below error. 
<img width="1680" alt="Screenshot 2021-02-17 at 7 37 46 PM" src="https://user-images.githubusercontent.com/22376778/108216031-ff0bf800-7157-11eb-869e-fff99505d701.png">

**Comment by brancz** [comment]
What version of Go are you using?

**Comment by avinashk442** [comment]
@brancz 
Below is output of go env :
<img width="963" alt="Screenshot 2021-02-18 at 12 32 39 AM" src="https://user-images.githubusercontent.com/22376778/108254472-114e5c00-7181-11eb-9512-fe7fcbe6a186.png">

Can I use docker container for capturing continuous profiling for any golang application?

**Comment by brancz** [comment]
Looks like you have a rather old go version. You might want to update it.

Yes you can absolutely use the docker container to capture profiles from go applications! You'll need to of course configure it (which you would need to do anyways) and mount the configuration into the container.

**Comment by brancz** [comment]
I'm writing up some instructions for using docker containers, maybe you can test those! :)

**Comment by brancz** [comment]
This works well for me. You can run it from the conprof repo root-directory.

```bash
docker run --network host --rm -it -v /etc/passwd:/etc/passwd -u `id -u`:`id -g` -v `pwd`:`pwd`:z -w `pwd` quay.io/conprof/conprof:master-2021-02-15-56c07ca all --config.file examples/conprof.yaml --http-address :10902 --storage.tsdb.path ./data
```

**Comment by brancz** [comment]
I added it to the quickstart docs, hopefully that will make it easier for the next person! :) https://github.com/conprof/conprof#quickstart

Let me know if this works for you!

**Comment by avinashk442** [comment]
@brancz Thanks for giving command but I am not getting how can I use the tool to monitor an application written in golang and that application is also running inside container. Can you please guide?
Do I need to add some files in my application software to connect with conprof?
How conprof container and application interact?
We can setup meeting on meet if you want.

**Comment by brancz** [comment]
I'm going to be writing up some getting started docs tomorrow, and then you can try them out! :)

**Comment by brancz** [comment]
We added a new [getting started](https://github.com/conprof/conprof#getting-started) section as well as a guide on how to [instrument your go app](https://github.com/conprof/conprof/blob/master/docs/instrumenting/go.md). Could you have a look at these? And if not I'm happy to do a call and understand where we're missing things! Thank you so much for bearing with us!

**Comment by brancz** [comment]
We have an all-new website that hopefully helps with getting started https://www.parca.dev/
