### ISSUE TITLE
Make profile types query time bound

### ISSUE THREAD

**Issue by brancz** [parca-dev/parca#1472]
There's no good reason for us to query profile types across all of time. We should query it for the time that is selected in the time selector. This will require both a backend and frontend change.

**Comment by manojVivek** [comment]
In the current UI layout, the profile selector is before the time selector, so it might not be very intuitive to the user that the profile type changes based on time selection. 

We need to find a way to make it obvious on the UI to the users that the profile type is time bound so that they might not think some profile types are missing.

**Comment by manojVivek** [comment]
The easiest we can do is move the time selector to the left:

<img width="983" alt="Screenshot 2022-08-02 at 12 08 35 PM" src="https://user-images.githubusercontent.com/1283424/182308589-5292180b-92c1-47cc-8c90-6e3096b350e5.png">


wdyt? 

@yomete @monicawoj Would love to hear your ideas as well.

**Comment by manojVivek** [comment]
We can also add a message to the profile selector drop down: 

<img width="826" alt="Screenshot 2022-08-02 at 12 15 21 PM" src="https://user-images.githubusercontent.com/1283424/182309556-4bff36e5-d006-4967-a080-bca00114b6e7.png">

**Comment by monicawoj** [comment]
I think the solutions you suggested, Manoj, are complementary. Might be good to have both. In regards to the time selector, it seems a little counter-intuitive for me to have it come before the profile type, but in regards to what depends on what (profile type dependent on time), I think this might be the logical way to go.

Another idea would be to disable the profile type dropdown until the user selects a time range, but that would mean not starting with a default time range.

**Comment by brancz** [comment]
On second thought I think maybe the backend should just be fast enough to answer these queries quickly. It's a query that should only touch very little amounts of data, so it should be possible to optimize a lot more. I'm going to close this, for now, to think about this some more. Sorry for the back and forth.
