### ISSUE TITLE
ui: Allow deletion of individual filter items from the Profile Selector. 

### ISSUE THREAD

**Issue by manojVivek** [parca-dev/parca#1537]
Add a `x` button to the filter items to remove them from the filters. Currently, we can only delete the filter items from the right to left with `backspace` key. 

<img width="778" alt="Screenshot 2022-08-11 at 11 32 35 AM" src="https://user-images.githubusercontent.com/1283424/184073179-6ee9f2c3-db54-43e7-ae0b-85e69a8d6c30.png">

**Comment by yomete** [comment]
Closing this as we no longer have this design in the query browser.
