### ISSUE TITLE
symbolizer: Missing symbols after a crash of the Parca Server

### ISSUE THREAD

**Issue by Pryz** [parca-dev/parca#1543]
I'm opening this issue on this repo but it is probably coming from a Parca Agent problem. We've noticed that after a crash of the Parca Server, and because as of no some deployments will not persist the metadata on disk or in a blob storage, symbols will be missing in the Parca UI.

From our discussion during the Parca Community call, the Parca Agent is supposed to cache those symbols and send those from time to time to the server. However this behavior seems to be broken right now. The only way of refreshing the symbols on the Parca Server will be to rolling restart all the agents.

I will try to take a look and give more information in the coming days.

**Comment by kakkoyun** [comment]
Just to make sure you have all the things you need, Parca Agent maintains a cache to prevent frequent checks for debug information. This means there will be a grace period until the agent asks the server if the debug information exists (2 minutes by default) and then tries to upload.

Could you validate this doesn't work after 2 minutes?

**Comment by maxbrunet** [comment]
The conversation during Parca Office Hours: https://youtu.be/cnzreWgmnSM?t=1020

> Could you validate this doesn't work after 2 minutes?

"Yeah, like it's not happening even after 10-15-20 minutes." (https://youtu.be/cnzreWgmnSM?t=1122)

**Comment by Pryz** [comment]
Finally have the time to take a look at this issue. Looks like the uploading cache doesn't expire: https://github.com/parca-dev/parca-agent/blob/a5523ea4665d046d5a0482309f40b61b987136f5/pkg/debuginfo/manager.go#L62-L64 and so we will never re-upload any debug info.

**Comment by kakkoyun** [comment]
Uploading cache is a local cache. By local I mean it doesn't cache a result from the remote API. And we manually remove the uploading state of the discovered object files. Maybe we have missed a failure scenario.

**Comment by PowerSurj** [comment]
I am running the latest Parca agent and the Parca server releases and observing the same issue.
Parca Agents don't resent the symbols.
