### ISSUE TITLE
ci: Make skipped required checks report success

### ISSUE THREAD

**Issue by kakkoyun** [parca-dev/parca#1567]
When the required CI checks are not marked as a success, the auto-merge won't work (especially important for the bots). Apparently, there's a way to do it that mentioned in the docs https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks

**Comment by maxbrunet** [comment]
This is why we use [fkirc/skip-duplicate-actions#skip-if-paths-not-changed](https://github.com/fkirc/skip-duplicate-actions#skip-if-paths-not-changed), as the link you shared says:

> If a job in a workflow is skipped due to a conditional, it will report its status as "Success".

Would you have an example PR you had an issue with?

**Comment by maxbrunet** [comment]
I think we got this covered for all workflows, I have not seen any blocking pending check in a long while.
