### ISSUE TITLE
Don't allow store-address flag when not in scraper only mode

### ISSUE THREAD

**Issue by thorfour** [parca-dev/parca#1572]
If you set the store-address flag you're likely expecting it to start shipping data to the remote storage. However if you don't set the mode to be scraper only it doesn't behave in that expected way.

We should have the Parca exit with an error suggesting that if you set `--store-address` that you should also set `--mode=scraper-only`

**Comment by boranx** [comment]
hey folks, I've recently started hacking on `parca` and like it so far! thanks for bringing these together
Although I'm not very confident in its code, I wanted to propose a small pr to fix this issue
