### ISSUE TITLE
Allow compressing gRPC calls

### ISSUE THREAD

**Issue by brancz** [parca-dev/parca#159]
Currently gRPC requests are uncompressed, we should allow compressing them with snappy. Something like: https://github.com/un000/grpc-snappy

**Comment by metalmatze** [comment]
With the storage using zstd going forward maybe it might be easier for consistency to use it here too? :thinking: 
I'm happy with snappy too though :)

**Comment by brancz** [comment]
Just a gut feeling, snappy tends to be very light on CPU, which is probably the right trade-off here it's not about optimal compression.

**Comment by metalmatze** [comment]
I see. That makes a lot of sense then! 👍

**Comment by brancz** [comment]
Obsolete
