### ISSUE TITLE
PathPrefix should also append a prefix to /api calls

### ISSUE THREAD

**Issue by TomHellier** [parca-dev/parca#1656]
I am trying out the continuous profiling tool on a cluster I operate, I really like it so far!

I typically deploy my applications on a subpath, for example: `example.com/parca/`

I attempted to use the Flag `PathPrefix`, but this appears to only work for the UI resources, and when the web app attempted to access the /api/ endpoint, it used `example.com/api/` instead of what I was expecting, `example.com/parca/api`

I tried to set the environment variable:
`REACT_APP_PUBLIC_API_ENDPOINT` to `https://example.com/parca/`, but I suspect that only works when running webpack dev server

**Comment by metalmatze** [comment]
Yes, seems like you're right.
The `grpcWebMux` gets registered against the `internalMux` and we don't use the prefix there...
https://github.com/parca-dev/parca/blob/main/pkg/server/server.go#L146
