### ISSUE TITLE
Make Source view show source code

### ISSUE THREAD

**Issue by bboreham** [parca-dev/parca#170]
Source view (for me, at least) just lists function names with source file name, and I guess that's because the server hasn't downloaded the source code.

Thinking out loud about possible implementation...
 * If the code is hosted in git, this could be done with a regex mapping from source file path to git repository.
 * Even better if conprof can download the correct version.  For my programs this can be extracted from the image tag, if there was a service discovery meta label `__meta_kubernetes_pod_container_image`.

**Comment by brancz** [comment]
I love this idea! I've been thinking about this for some time as well (an additional awesome thing would be to integrate directly with GitHub codespaces and/or GitPod). I wonder if we could make it a configuration option in the config file how to discover the code location (maybe it has to be relabeled into a specific label?). Like let's say `conprof_code_url="https://github.com/kubernetes/kube-state-metrics/blob/b79d17d4d627560945c063e60faa82be79f00089"`.

**Comment by 26tanishabanik** [comment]
Hi @brancz , is the idea mentioned in this issue on the enhancements list?

**Comment by yomete** [comment]
Closing this as we now have this feature.
