### ISSUE TITLE
Writing obsolete blocks

### ISSUE THREAD

**Issue by bboreham** [parca-dev/parca#183]
After I deleted some of the oldest data to un-stick #182, I saw this:

```
[...]
level=info ts=2021-04-06T08:13:48.606908744Z caller=head.go:717 msg="WAL segment loaded" segment=1846 maxSegment=1847
level=info ts=2021-04-06T08:13:48.607210966Z caller=head.go:717 msg="WAL segment loaded" segment=1847 maxSegment=1847
level=info ts=2021-04-06T08:13:48.608005243Z caller=head.go:722 msg="WAL replay completed" checkpoint_replay_duration=27.851045ms wal_replay_duration=6m55.553130494s total_replay_duration=19m7.563209293s
level=info ts=2021-04-06T08:13:48.698233295Z caller=http.go:58 service=http/server component=all msg="listening for requests and metrics" address=:8080
level=info ts=2021-04-06T08:14:02.923087176Z caller=compact.go:506 msg="write block" mint=1616853600000 maxt=1616860800000 ulid=01F2K3XKNDX4JZ3D875G0HW4PH duration=5.629312496s
[...]
level=info ts=2021-04-06T08:16:38.538969567Z caller=db.go:1189 msg="Deleting obsolete block" block=01F2K3XKNDX4JZ3D875G0HW4PH
```

1616860800000 is 2021-03-27T16:00:00Z and I have ` - --storage.tsdb.retention.time=48h` so it could have saved a bit of effort.

**Comment by brancz** [comment]
hmm .. This sounds like for some reason compaction isn't triggering. Otherwise, that block should have been deleted? Or are you saying since that block was already out of range when loading, it should have just been deleted immediately before replaying the WAL in the first place?

**Comment by brancz** [comment]
Nevermind. I understand now. Yeah, writing blocks that are already out of range is kind of silly, I agree.

**Comment by brancz** [comment]
We have an entirely new storage engine that we introduced with the Conprof -> Parca rebrand. :)

Closing here.
