### ISSUE TITLE
Strange empty query result returned

### ISSUE THREAD

**Issue by lilic** [parca-dev/parca#1868]
[Query parca with `namespace=""` ](https://demo.parca.dev/?currentProfileView=icicle&expression_a=parca_agent_cpu%3Asamples%3Acount%3Acpu%3Ananoseconds%3Adelta%7Bnamespace%3D%22%22%7D&from_a=1665509931952&to_a=1665510831952&merge_a=false&time_selection_a=relative:minute|15)(which I by mistake clicked as it's now always a first option, unsure if this is intended) 

<img width="1438" alt="Screenshot 2022-10-11 at 19 56 42" src="https://user-images.githubusercontent.com/6232346/195164996-8f4c8421-9bad-4c8e-90ae-4a90bd76b879.png">

Then in another query same time [run a blank query](https://demo.parca.dev/?currentProfileView=icicle&expression_a=parca_agent_cpu%3Asamples%3Acount%3Acpu%3Ananoseconds%3Adelta%7B%7D&from_a=1665509975756&to_a=1665510875756&merge_a=false&time_selection_a=relative:minute|15)
<img width="1434" alt="Screenshot 2022-10-11 at 19 56 30" src="https://user-images.githubusercontent.com/6232346/195164946-7c475410-fa4e-4606-9977-2886ab0be216.png">

We see the two selected processes both match (from my 👀 at least) in both the graphs, but according to the `""` query it did not exist before a few minutes ago.

So essentially we get two different results when querying with empty namespace and when we query all.

**Comment by metalmatze** [comment]
Very interesting find. While trying to understand the problem I was trying to narrow it down even more. So if we query for the same `pid` in both, the same behavior shows up. This is clearly a bug. Good find!

![all](https://user-images.githubusercontent.com/872251/195329430-6d119536-0e8f-4819-a66a-8664a2085546.png)
![namespace](https://user-images.githubusercontent.com/872251/195329435-2a4d6579-1915-4209-9330-acc492e36b14.png)
