### ISSUE TITLE
UI Bug - Invalid date

### ISSUE THREAD

**Issue by syepes** [parca-dev/parca#192]
Don't know if someone else has reported this but, when trying to change the From date with Firefox (On Linux) the field gets the following error: Invalid date

![image](https://user-images.githubusercontent.com/333081/116204784-625c6c80-a73d-11eb-9368-029d274646bb.png)

**Comment by brancz** [comment]
We'll have to look into that one, not sure what's happening. Thank you for reporting!

**Comment by brancz** [comment]
We have an entirely new UI with the Conprof -> Parca rebrand :)
