### ISSUE TITLE
Error building ui with `node@18.11.0`

### ISSUE THREAD

**Issue by asubiotto** [parca-dev/parca#1952]
Running `make build`:
```
warning geotiff@2.0.4: The engine "browsers" appears to be invalid.
error eslint-plugin-jsdoc@38.0.6: The engine "node" is incompatible with this module. Expected version "^12 || ^14 || ^16 || ^17". Got "18.11.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
make: *** [ui/build] Error 1
```

Downgrading `node` using `brew link node@16` works. I don't know enough about node package management to have a quick fix.

**Comment by maxbrunet** [comment]
We support LTS versions, currently 16 is the latest. Many dependencies do the same, engines requirements will likely be relaxed when 18 will transition to LTS

https://endoflife.date/nodejs

**Comment by asubiotto** [comment]
Thanks
