### ISSUE TITLE
ui: Make time format consistent across summary and input fields

### ISSUE THREAD

**Issue by Sylfrena** [parca-dev/parca#2024]
Currently, the dropdown time-selector menu uses two different time formats for the input field(`November 2`) and the summary field(`2 Nov`). We should use a consistent format across both.
![image](https://user-images.githubusercontent.com/35404119/199466211-9d63a627-1384-45bd-a07f-f4915922e254.png)

**Comment by metalmatze** [comment]
Given that we use UTC and follow Prometheus mostly, we should probably change the formatting to `yyyy-MM-dd HH:mm:ss` (right now would be `2023-04-04 09:13:30`) across the board. We can still use relative formatting where applicable, but overall whenever using absolute values this is what we should settle on.

**Comment by yomete** [comment]
Fixed in #2920
