### ISSUE TITLE
Symbolizer: Handle the object files with only .dynsym sections properly

### ISSUE THREAD

**Issue by v-thakkar** [parca-dev/parca#2056]
With the changes in #1930 , we're only looking for .symtab section in object files but a lot of object files only have .dynsym which then has a link to .symtab section. Example errors while opening `libpython3.10.so.1.0` can be seen in https://github.com/parca-dev/parca-agent/issues/933 . 

Partial output of `readelf -S /usr/lib/x86_64-linux-gnu/libpython3.10.so.1.0`

```
There are 33 section headers, starting at offset 0x592ec0:

Section Headers:
  [Nr] Name              Type             Address           Offset
       Size              EntSize          Flags  Link  Info  Align
  [ 0]                   NULL             0000000000000000  00000000
       0000000000000000  0000000000000000           0     0     0
  [ 1] .note.gnu.pr[...] NOTE             00000000000002a8  000002a8
       0000000000000020  0000000000000000   A       0     0     8
  [ 2] .note.gnu.bu[...] NOTE             00000000000002c8  000002c8
       0000000000000024  0000000000000000   A       0     0     4
  [ 3] .gnu.hash         GNU_HASH         00000000000002f0  000002f0
       00000000000031d4  0000000000000000   A       4     0     8
  [ 4] .dynsym           DYNSYM           00000000000034c8  000034c8
       000000000000cc30  0000000000000018   A       5     1     8
  [ 5] .dynstr           STRTAB           00000000000100f8  000100f8
       00000000000099ab  0000000000000000   A       0     0     1
  [ 6] .gnu.version      VERSYM           0000000000019aa4  00019aa4
       0000000000001104  0000000000000002   A       4     0     2
  [ 7] .gnu.version_r    VERNEED          000000000001aba8  0001aba8
       00000000000001c0  0000000000000000   A       5     3     8
  [ 8] .rela.dyn         RELA             000000000001ad68  0001ad68
       000000000004ed50  0000000000000018   A       4     0     8
```
Line of .dynsym table where the link of .symtab is:
```
1333: 00000000002fdf70    16 FUNC    GLOBAL DEFAULT   14 PyInit__symtable
```
Just reverting the change wouldn't work though because previously we were just appending `.symtab + .dynsym` which results in the wrong table. So I'm looking into the proper fix for this. Opening this issue to keep track of the progress.

**Comment by v-thakkar** [comment]
The interesting thing is libraries like `libc` also don't have .symtab but we seem to be symbolizing it somewhat correctly. So gonna check a bunch of those things to make sure that our ELF symbolizer works for all.

**Comment by kakkoyun** [comment]
> The interesting thing is libraries like `libc` also don't have .symtab but we seem to be symbolizing it somewhat correctly via our ELF symbolizer. So gonna check a bunch of those things to make sure that our ELF symbolizer works for all.

I'd say let's make sure we actually use symtab add2line not DWARF add2line.

**Comment by v-thakkar** [comment]
Unassigned myself as I wouldn't be able to tackle it in the next few weeks. Happy to review and test the PR if anybody would like to pick it up. Will come back to it in a month if it'll be still open. :)
