### ISSUE TITLE
parca CLI does not handle HTTP redirects

### ISSUE THREAD

**Issue by umanwizard** [parca-dev/parca#2075]
An HTTP code 308 simply causes the scraper to fail

**Comment by brancz** [comment]
Can you describe the setup a bit more? If it's a permanent redirect, why not just point the scraper at the redirected path?

**Comment by umanwizard** [comment]
I can and did, but it took me a while to figure out what the problem was, because it was just silently failing: there was no error message until I figured out how to run the CLI with Debug log level.

**Comment by brancz** [comment]
I see. I agree that at the very least the error and action should be crystal clear!

**Comment by umanwizard** [comment]
It would be nice to also print the path that the redirect is pointing to

**Comment by brancz** [comment]
Makes sense!

**Comment by ShubhamPalriwala** [comment]
Hey @brancz, I would like to take this up as my starter point with Parca.
As of now
- I have compiled parca source locally
- Read the Profiling 101 from the official docs

It'd be great if you could help me what should be my next steps for the same :))
