### ISSUE TITLE
Feature request: handle uncompressed pprof files

### ISSUE THREAD

**Issue by umanwizard** [parca-dev/parca#2076]
The pprof documentation says they must be gzipped, so Parca is not technically out of spec here for choking on uncompressed files. However, the Google pprof tool handles uncompressed files fine, so it’s possible for someone generating pprof files but forgetting the compression step to be confused why they don’t work in Parca. (This happened to me last night 😅)

**Comment by ShubhamPalriwala** [comment]
Hey, I would like to work on this but before that, can you help me find some resources I can read upon as I'm entirely unaware of pprof, gzipped, uncompressed files, their generation, etx.

It seems like a good learning curve for me ")) Also, in the meantime I'm googling and going through these terms on my own so see how much I myself can grasp

**Comment by umanwizard** [comment]
* Pprof -- a set of tools from Google for generating and analyzing/visualizing profiler data.
* Gzip -- A compression algorithm (you surely have `gzip` and `gunzip` programs installed if you run Linux)
* Uncompressed file -- here I mean a file that has _not_ been compressed with `gzip`

The file format used by pprof is normally compressed using `gzip`, but the [visualization tool](https://github.com/google/pprof) is also able to work fine with uncompressed files. Parca is capable of reading files in the same format, but it assumes they are compressed with gzip, and is not able to work with uncompressed files (unlike the Google pprof tool).

**Comment by brancz** [comment]
Apologies for not updating here sooner, but this was closed by https://github.com/parca-dev/parca/pull/2751
