### ISSUE TITLE
Implement symbol resolution in-process

### ISSUE THREAD

**Issue by brancz** [parca-dev/parca#213]
Out of simplicity we use `addr2line` for resolving symbols currently, this is problematic for various reasons:

* We have to have the llvm tools installed to do this, which makes development, CI, etc. more complicated as versions of tooling need to be the same
* We shell out to the command for every symbol resolution
* We can only resolve one symbol at a time when we could actually do it in bulk

**Comment by kakkoyun** [comment]
#314
