### ISSUE TITLE
Flamegraph - coloured stacks based on the binary name

### ISSUE THREAD

**Issue by manojVivek** [parca-dev/parca#2145]
Request from Discord: https://discord.com/channels/877547706334199818/877547706334199821/1042763253849272320

**Comment by Cluas** [comment]
package name is better

**Comment by brancz** [comment]
I think both could be useful?

**Comment by Cluas** [comment]
Can we adjust the transparency of the color in proportion to the value, so that it is easy to see which piece wastes the most resources.

**Comment by brancz** [comment]
The width of a span already shows the value, no? I don't really see how color makes that better. Color to group pieces of code does make sense I think.

**Comment by Cluas** [comment]
> The width of a span already shows the value, no? I don't really see how color makes that better. Color to group pieces of code does make sense I think.

by example:
![20221118-175256](https://user-images.githubusercontent.com/10056928/202673673-68bbf85d-a8d9-461b-8160-125b71fc78c5.jpeg)

**Comment by Cluas** [comment]
Of course I agree that the modules can be differentiated according to different colors, and different transparency can look more like flames.

**Comment by brancz** [comment]
I don't think we should do something just to make it look like flames or icicles, we should focus on providing meaning. I think providing the same meaning through two visual clues is not making effective use, but I think coloring packages and or binaries differently is very useful.

**Comment by metalmatze** [comment]
I'd vote for just going with binaries / mappings for now.
Especially in bigger flame graphs going with colors by package will be too much different color again, such that it just becomes noise.

We can always iterate after having tried with the binaries first.

**Comment by Cluas** [comment]
how about 
![image](https://user-images.githubusercontent.com/10056928/202733016-484d7ae7-24e9-43ab-855f-3f0938650e0b.png)

**Comment by kakkoyun** [comment]
One other color distinction can be between user calls, runtime calls, and system calls (kernel).

**Comment by leeoniya** [comment]
Grafana viz dev here :wave: 

for our FlameGraph panel, we may consider simply allowing arbitrary fields to be used for coloring via [Value mappings](https://grafana.com/docs/grafana/latest/panels-visualizations/configure-value-mappings/) or [Thresholds](https://grafana.com/docs/grafana/latest/panels-visualizations/configure-thresholds/).

our current (WIP) profile DataFrame structure looks like this:

level|value|self|label
-|-|-|-
0|100|12|root
1|40|1|func1
1|30|15|func2
2|15|3|func3
```

so theoretically, additional columns (fields) can be added at-will and configured to represent node color, act as data links, etc.
