### ISSUE TITLE
--cors-allowed-origins issue

### ISSUE THREAD

**Issue by calvinxu** [parca-dev/parca#2146]
Hi, 
When deploy parca in kubernetes, and create the data source on grafana, when I tried to add panel using the data source, this error cause failed to retrive the data from data source, 
![image](https://user-images.githubusercontent.com/1214528/202629499-393670de-5a1f-4ad2-b18a-4b56d41d0957.png)
I did check that the parca server is started with --cors-allowed-origins='*', could you help me out on this?

![image](https://user-images.githubusercontent.com/1214528/202629399-532ef99d-7244-4841-b405-3048ab67b354.png)

**Comment by brancz** [comment]
I feel like this error might not be cors related? What is the query you tried to run?

cc @manojVivek to double check regarding cors

**Comment by manojVivek** [comment]
The cors configuration looks good to me as well.

Would it be possible for you to open the browser console and check if there are any errors logged?

**Comment by calvinxu** [comment]
the query return error{}, I'm not sure what is the problem there, on the parca server UI, it is a little bit abnormal

![image](https://user-images.githubusercontent.com/1214528/203252681-45493ba3-1a17-463b-aeb7-80bc89406bc3.png)

![image](https://user-images.githubusercontent.com/1214528/203252857-81b25cfd-087f-4e79-8f85-d96020e63541.png)

I launched 4 parca agent along with the parca server
NAME                     READY   STATUS    RESTARTS      AGE
parca-6999dd4b77-pjb4l   1/1     Running   0             3d23h
parca-agent-jgrzd        1/1     Running   2 (38m ago)   3d23h
parca-agent-lgf5j        1/1     Running   0             3d23h
parca-agent-tchfj        1/1     Running   0             3d23h
parca-agent-xfl27        1/1     Running   0             3d23h

there is data from the agent show as below
![image](https://user-images.githubusercontent.com/1214528/203253281-ec608c76-f695-4c3f-940f-361b83dee7a8.png)

have no idea why the parca server doesn't show any continuous curve line but just some dot/points

![image](https://user-images.githubusercontent.com/1214528/203253638-252fedc2-d29a-45b5-bc76-81d961824e1d.png)

![image](https://user-images.githubusercontent.com/1214528/203254929-303d5913-9fc8-4540-bb2e-75ae8abead1b.png)

**Comment by calvinxu** [comment]
how to interpret this info "No profile taken in the last 11s that matches the requested label-matchers query. Profiles are taken every 10s so either the profiler matching the label-set has stopped profiling, or the label-set was incorrect." 

![image](https://user-images.githubusercontent.com/1214528/203318658-71d233d7-cebb-4ca5-a4c7-ee199ddbb808.png)

**Comment by brancz** [comment]
I have a feeling this is not at all cors related, but much rather the same problem as reported in https://github.com/parca-dev/parca-agent/issues/1060

**Comment by brancz** [comment]
Could this potentially be a time synchronization issue? We've certainly seen issues with time synchronization before. Are you running the Parca Agent and Parca server on a different machine that you're using your browser on?

**Comment by brancz** [comment]
If so, could you run `date` on all machines and share the output?

**Comment by calvinxu** [comment]
eventually the issue gone with latest release
