### ISSUE TITLE
feature request: load data once switching between tabs

### ISSUE THREAD

**Issue by Cluas** [parca-dev/parca#2148]
![20221118-184338](https://user-images.githubusercontent.com/10056928/202686242-01720b3a-66f9-4734-950c-5ab168397b74.jpeg)

currently, switch tab button will fetch data from backend again, although there are no request parameter changes, data should load once

**Comment by brancz** [comment]
cc @manojVivek @monicawoj @yomete 

There is also a part of this in the backend that we should consider, as we query the entire database again, whereas each visualization renders off of the same result, so we should cache the database result and only re-render the different representation.

**Comment by Cluas** [comment]
lru cache will be helpful.

**Comment by brancz** [comment]
Definitely!

**Comment by manojVivek** [comment]
> There is also a part of this in the backend that we should consider, as we query the entire database again, whereas each visualization renders off of the same result, so we should cache the database result and only re-render the different representation.

The query data is already cached, but the cache lib(`react-query`) does a query refresh on tab switch by default. There is a flag to disable this behaviour. Will take care of it.

**Comment by manojVivek** [comment]
Sorry, I misspoke, we didn't have `react-query` caching on Parca. I just added that with this PR: https://github.com/parca-dev/parca/pull/2173
