### ISSUE TITLE
Unexpected series returned

### ISSUE THREAD

**Issue by yeya24** [parca-dev/parca#222]
Version:
agent v0.1.0-alpha
server v0.1.0-alpha

I got no series returned with query `container="thanos"`
![image](https://user-images.githubusercontent.com/25150124/136109738-f68bf1fc-bff6-4fe8-bdcf-c5c40371f3be.png)

But if I query `namespace=xxx, container=thanos` together, I got lots of incorrect series returned. I expected to get no series returned as well.
![image](https://user-images.githubusercontent.com/25150124/136110067-d07b36bf-446a-4d9b-9033-712e3a4e9b06.png)

**Comment by brancz** [comment]
Thank you for reporting, this should indeed not be happening!

**Comment by thorfour** [comment]
This was fixed with https://github.com/parca-dev/parca/pull/247
