### ISSUE TITLE
Allow using signed object storage URLs for uploads

### ISSUE THREAD

**Issue by brancz** [parca-dev/parca#2237]
Our home-brewed gRPC uploads are fine for environments where for example non-cloud-provider object storage or filesystem providers are used, but when using a cloud-provider object storage it unnecessarily complicates things and lots of ups are left on the table.

I propose a new configuration in the config file root:

```
signed_uploads:
  limits:
    time: <duration>
    size: <number_of_bytes>
```

If specified, then we assume we want to use the already configured object storage bucket with signed URLs for uploads.

For a start, since it's the only one I personally need I will only implement Google Cloud Storage support, but I already checked and AWS S3 supports limiting bytes and duration as well.

The existing APIs that we already have will continue to exist, but I am proposing two additional APIs to be added to the debuginfo gRPC service:

```
rpc InitiateUpload(InitiateUploadRequest) returns (InitiateUploadResponse) {}
rpc MarkUploadFinished(MarkUploadFinishedRequest) returns (MarkUploadFinishedResponse) {}

message InitiateUploadRequest {
  string build_id = 1;
  int64 size = 2;
}

message InitiateUploadResponse {
  enum UploadStrategy {
    UPLOAD_STRATEGY_UNKNOWN_UNSPECIFIED = 0;
    UPLOAD_STRATEGY_GRPC = 1;
    UPLOAD_STRATEGY_SIGNED_URL = 2;
  }

  string upload_id = 1;
  UploadStrategy upload_strategy = 2;
  string signed_url = 3;
}

message MarkUploadFinishedRequest {
  string upload_id = 1;
  string build_id = 2;
}

message MarkUploadFinishedResponse {}
```

The flow from the perspective of the parca-agent changes slightly. Instead of immediately starting the upload if an `.Exists` request returns the build ID doesn't already exist, it extracts the debuginfos from the binary and gets its size. Using the size, it issues an `InitiateUploadRequest` using that size.

Regardless of signed URLs are configured or not, the server generates a unique UUID to identify the upload. If signed URLs are disabled, then the server just responds with the upload strategy being the gRPC-based upload that we have today and the upload ID. If signed URLs are configured, then the server notes in metadata that the upload started `time.Now()` and generates the signed URL to expire at the start time plus `<configured time limit>` and with the specified limit. Exists requests and initiate requests don't allow new uploads until additional 2 minutes after the URL expires (to account for some time synchronization issues).

gRPC uploads also change slightly in this model. They will no longer validate uploads on the fly, this is deferred to the files actually being used by the symbolizer (for example to mark them corrupted).

The parca-agent (or any other client doing uploads) then uses the respective upload strategy to upload the debuginfos, and when done issues the `MarkUploadFinshed` request marking the upload done in the metadata.

cc @metalmatze @kakkoyun @javierhonduco

**Comment by metalmatze** [comment]
Seems sound and solid to me.
I've never used signed URLs programmatically. It seems like a really good option here indeed!

**Comment by brancz** [comment]
Closed by https://github.com/parca-dev/parca/pull/2248
