### ISSUE TITLE
Q: Redis Keys at point in time use case?

### ISSUE THREAD

**Issue by naseemkullah** [parca-dev/parca#25]
Hi,
I was wondering if this tool will solve the following use case:

To know the values of redis keys (which are in memory) at any point in time.

Thanks.

**Comment by brancz** [comment]
I don't think this is the tool you're looking for. Conprof ingests standard pprof profiles, if you can get that data into a pprof profile then maybe, but it sounds like you rather want something like string type metrics or something like that (or normal metrics if the values of these keys are of numbered values).
