### ISSUE TITLE
Callgraph panics and Parca goes blank

### ISSUE THREAD

**Issue by metalmatze** [parca-dev/parca#2505]
With the current version of Parca (`v0.15.0-3ff66f58`) once the callgraph is activated the page goes blank. 

This is what the dev tools show.
![Screenshot_from_2023-01-26_14-52-46](https://user-images.githubusercontent.com/872251/215742402-16fe7a91-1d8e-4076-a465-b42abadb71ff.png)

**Comment by rawkode** [comment]
This still panics with the same errors for me, v0.17.0

cc @monicawoj

**Comment by monicawoj** [comment]
> This still panics with the same errors for me, v0.17.0
> 
> cc @monicawoj

Thanks for flagging that @rawkode, I'll take another look.
