### ISSUE TITLE
Fix license pre-commit hook

### ISSUE THREAD

**Issue by brancz** [parca-dev/parca#2599]
Essentially the same as https://github.com/parca-dev/parca-agent/pull/1261, but for this repository.

**Comment by Franqsanz** [comment]
Hi, I wanted to know if you only have to make the change in the `.pre-commit-config.yaml` file or also in the rest as here [https://github.com/parca-dev/parca-agent/pull/1261](https://github.com/parca-dev/parca-agent/pull/1261)?

**Comment by maxbrunet** [comment]
> Hi, I wanted to know if you only have to make the change in the `.pre-commit-config.yaml` file or also in the rest as here [parca-dev/parca-agent#1261](https://github.com/parca-dev/parca-agent/pull/1261)?

Once reconfigured, `pre-commit` will take care of the rest, it can be run on all files manually or the automation will do it when the PR is opened
