### ISSUE TITLE
icicle graph shows all memory attributed to {external}, while the old pprof UI shows specific users

### ISSUE THREAD

**Issue by roy-t** [parca-dev/parca#261]
The icicle graph doesn't specify who uses the memory:

![image](https://user-images.githubusercontent.com/623634/136416260-20816164-457f-4841-9551-818519672f4c.png)

As you can see everything is attributed to `{external}`.

Looking at the same application using the old pprof UI the icicle graph looks like this:

![image](https://user-images.githubusercontent.com/623634/136416424-aca25a5a-43b4-472f-bef0-0aeaeb32bb50.png)

I've attached the heap and profile my application provides on /debug/pprof/heap and /debug/pprof/profile in the attached zip file.
[pprof.zip](https://github.com/parca-dev/parca/files/7304993/pprof.zip)

**Comment by brancz** [comment]
@adrien-f I believe you were right. Merged this in #392, could y'all try to test this with the latest image from main? `ghcr.io/parca-dev/parca:main-1e755b90`

**Comment by brancz** [comment]
> I suppose the Cumulative value is related to #382 ? I'll follow there eyes !

Correct!
