### ISSUE TITLE
in parca v0.14.0, server memory is rising

### ISSUE THREAD

**Issue by zdyj3170101136** [parca-dev/parca#2621]
#### version
 parca v0.14.0

#### problem
when i enable scrape for 20 parca-agent.
the parca server's memory usage is increasing.
![截屏2023-02-17 下午3 52 28](https://user-images.githubusercontent.com/52686065/219583982-f1e21782-6473-4ca9-a843-f618f3d61c42.png)

here is the memory pprof.
[profile - 2023-02-17T155316.110.pb.gz](https://github.com/parca-dev/parca/files/10764530/profile.-.2023-02-17T155316.110.pb.gz)

seems most of memory is allocated by handlerStream (debuginfo upload).
do you know why?
![截屏2023-02-17 下午3 54 24](https://user-images.githubusercontent.com/52686065/219584484-04fa1f6f-782f-4bd8-9bf9-821f90658664.png)

**Comment by brancz** [comment]
The periodic increase and drop is expected, but the profile does look interesting.

Can you describe your setup in more detail? Are you doing profile scraping in addition to parca-agent?

> seems most of memory is allocated by handlerStream (debuginfo upload).

The home-grown uploads really should not be used in production, can you try using signed uploads?

**Comment by zdyj3170101136** [comment]
> 周期性的上升和下降是预料之中的，但是这个配置文件看起来确实很有趣。
> 
> 你能更详细地描述你的设置吗？除了 parca-agent 之外，您是否还在进行配置文件抓取？
> 
> > 似乎大部分内存是由 handlerStream（调试信息上传）分配的。
> 
> 自制上传真的不应该用于生产，你可以尝试使用签名上传吗？

i find the reason is the high latency of oss upload.

in first situation, i only read all bytes from stream but not upload.
in second situation, i read all bytes from stream and upload.

here is the grpc upload method duration.
the bucket upload cost 10x latency.
![截屏2023-02-17 下午6 23 51](https://user-images.githubusercontent.com/52686065/219618408-e0dd802e-62cb-47de-b26b-f2c2aee6acbb.png)

here is the memory usage.
in second situation, the memory usage is much higher.
![截屏2023-02-17 下午6 25 27](https://user-images.githubusercontent.com/52686065/219618737-fdd9bf6c-7f1c-463c-92ed-68cea820672f.png)

so the high latency of oss lead to high memory usage.

**Comment by gites** [comment]
Great job with memory improvements in Parca v0.17.0

<img width="877" alt="Screenshot 2023-03-30 at 08 37 45" src="https://user-images.githubusercontent.com/10206601/228750337-c6c16fe9-4e3d-496b-9d87-6488f1c1d271.png">

Yellow is memory usage for Parca v0.16.2, green for v0.17.0
