### ISSUE TITLE
Error Building Parca on Apple M1 Macbook Pro

### ISSUE THREAD

**Issue by D-sense** [parca-dev/parca#2682]
Hi,

I am new here and trying to "build" Parca on my machine, Apple M1. While trying to build with `make build`, I got this error:

> cd ui && yarn --prefer-offline && yarn bootstrap && yarn build
yarn install v1.19.0
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
warning Pattern ["@grafana/ui@latest"] is trying to unpack in the same destination "/Users/adeshina/Library/Caches/Yarn/v5/npm-@grafana-ui-9.3.6-81c3cc4c8f0045bf0a9648cbdab1db4f40c9d502/node_modules/@grafana/ui" as pattern ["@grafana/ui@9.3.6","@grafana/ui@9.3.6","@grafana/ui@9.3.6"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["@types/lodash@latest"] is trying to unpack in the same destination "/Users/adeshina/Library/Caches/Yarn/v5/npm-@types-lodash-4.14.191-09511e7f7cba275acd8b419ddac8da9a6a79e2fa/node_modules/@types/lodash" as pattern ["@types/lodash@^4.14.167","@types/lodash@*"]. This could result in non-deterministic behavior, skipping.
info @swc/core-darwin-x64@1.3.36: The CPU architecture "arm64" is incompatible with this module.
info "@swc/core-darwin-x64@1.3.36" is an optional dependency and failed compatibility check. Excluding it from installation.
info @swc/core-linux-arm-gnueabihf@1.3.36: The platform "darwin" is incompatible with this module.
info "@swc/core-linux-arm-gnueabihf@1.3.36" is an optional dependency and failed compatibility check. Excluding it from installation.
info @swc/core-linux-arm-gnueabihf@1.3.36: The CPU architecture "arm64" is incompatible with this module.
info @swc/core-linux-arm64-gnu@1.3.36: The platform "darwin" is incompatible with this module.
info "@swc/core-linux-arm64-gnu@1.3.36" is an optional dependency and failed compatibility check. Excluding it from installation.
info @swc/core-linux-arm64-musl@1.3.36: The platform "darwin" is incompatible with this module.
info "@swc/core-linux-arm64-musl@1.3.36" is an optional dependency and failed compatibility check. Excluding it from installation.
info @swc/core-linux-x64-gnu@1.3.36: The platform "darwin" is incompatible with this module.
info "@swc/core-linux-x64-gnu@1.3.36" is an optional dependency and failed compatibility check. Excluding it from installation.
info @swc/core-linux-x64-gnu@1.3.36: The CPU architecture "arm64" is incompatible with this module.
info @swc/core-linux-x64-musl@1.3.36: The platform "darwin" is incompatible with this module.
info "@swc/core-linux-x64-musl@1.3.36" is an optional dependency and failed compatibility check. Excluding it from installation.
info @swc/core-linux-x64-musl@1.3.36: The CPU architecture "arm64" is incompatible with this module.
info @swc/core-win32-arm64-msvc@1.3.36: The platform "darwin" is incompatible with this module.
info "@swc/core-win32-arm64-msvc@1.3.36" is an optional dependency and failed compatibility check. Excluding it from installation.
info @swc/core-win32-ia32-msvc@1.3.36: The platform "darwin" is incompatible with this module.
info "@swc/core-win32-ia32-msvc@1.3.36" is an optional dependency and failed compatibility check. Excluding it from installation.
info @swc/core-win32-ia32-msvc@1.3.36: The CPU architecture "arm64" is incompatible with this module.
info @swc/core-win32-x64-msvc@1.3.36: The platform "darwin" is incompatible with this module.
info "@swc/core-win32-x64-msvc@1.3.36" is an optional dependency and failed compatibility check. Excluding it from installation.
info @swc/core-win32-x64-msvc@1.3.36: The CPU architecture "arm64" is incompatible with this module.
info @nrwl/nx-darwin-x64@15.7.2: The CPU architecture "arm64" is incompatible with this module.
info "@nrwl/nx-darwin-x64@15.7.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info @nrwl/nx-linux-arm-gnueabihf@15.7.2: The platform "darwin" is incompatible with this module.
info "@nrwl/nx-linux-arm-gnueabihf@15.7.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info @nrwl/nx-linux-arm-gnueabihf@15.7.2: The CPU architecture "arm64" is incompatible with this module.
info @nrwl/nx-linux-arm64-gnu@15.7.2: The platform "darwin" is incompatible with this module.
info "@nrwl/nx-linux-arm64-gnu@15.7.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info @nrwl/nx-linux-arm64-musl@15.7.2: The platform "darwin" is incompatible with this module.
info "@nrwl/nx-linux-arm64-musl@15.7.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info @nrwl/nx-linux-x64-gnu@15.7.2: The platform "darwin" is incompatible with this module.
info "@nrwl/nx-linux-x64-gnu@15.7.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info @nrwl/nx-linux-x64-gnu@15.7.2: The CPU architecture "arm64" is incompatible with this module.
info @nrwl/nx-linux-x64-musl@15.7.2: The platform "darwin" is incompatible with this module.
info "@nrwl/nx-linux-x64-musl@15.7.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info @nrwl/nx-linux-x64-musl@15.7.2: The CPU architecture "arm64" is incompatible with this module.
info @nrwl/nx-win32-arm64-msvc@15.7.2: The platform "darwin" is incompatible with this module.
info "@nrwl/nx-win32-arm64-msvc@15.7.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info @nrwl/nx-win32-x64-msvc@15.7.2: The platform "darwin" is incompatible with this module.
info "@nrwl/nx-win32-x64-msvc@15.7.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info @nrwl/nx-win32-x64-msvc@15.7.2: The CPU architecture "arm64" is incompatible with this module.
warning geotiff@2.0.4: The engine "browsers" appears to be invalid.
error eslint-plugin-jsdoc@38.0.6: The engine "node" is incompatible with this module. Expected version "^12 || ^14 || ^16 || ^17". Got "18.14.2"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
make: *** [ui/build] Error 1 

Is this a known issue with M1 machines? Please can anyone help?

**Comment by maxbrunet** [comment]
Hello @D-sense :wave:

> error eslint-plugin-jsdoc@38.0.6: The engine "node" is incompatible with this module. Expected version "^12 || ^14 || ^16 || ^17". Got "18.14.2"

This is #2540. Node 16 is required for now.

**Comment by D-sense** [comment]
Hi @maxbrunet,

Thanks for your help. Downgrading Nodde 16 works fine. The error message was a bit unclear as it says 12v to 17v is expected, which isn't the case when I initially downgraded Node to 17.
