### ISSUE TITLE
ui: DateTimePicker should support seconds as input

### ISSUE THREAD

**Issue by metalmatze** [parca-dev/parca#2757]
The Parca DateTimePicker only supports dates with hours and minutes.
Parca stores timestamps with milliseconds granularity. While we could show milliseconds too, we can probably only enable seconds. Prometheus takes in hours, seconds, and milliseconds only too. 

![datetimepicker](https://user-images.githubusercontent.com/872251/225100219-58585a20-a633-49c0-bb48-e5a0d2f21925.png)

**Comment by metalmatze** [comment]
On a related note, UTC uses 24-hour times. No am and pm. Maybe if we update the DateTimePicker we can adjust from the 12-hour to the 24-hour too.

**Comment by yomete** [comment]
Closing this as we now have this in the new date-time range picker.

<img width="1530" alt="image" src="https://github.com/parca-dev/parca/assets/9016992/1a647c22-1ea9-4f35-b86f-462f6b7ce5a4">
