### ISSUE TITLE
Zombie [llvm-symbolizer] process accumulated in parca container 

### ISSUE THREAD

**Issue by zq-david-wang** [parca-dev/parca#276]
I am trying to run parca/parca-agent in docker and collecting dockerd profile data.
My dockerd has docker-init setup to reap zombie processes, but within parca container, zombie processes keep accumulating, up to thousands before I restart the container.

```
~ $ ps aux
PID   USER     TIME  COMMAND
    1 nobody    0:00 /sbin/docker-init -- /parca
    8 nobody    4:18 /parca
   30 nobody    0:00 [llvm-symbolizer]
   31 nobody    0:00 [llvm-symbolizer]
   32 nobody    0:00 [llvm-symbolizer]
   33 nobody    0:00 [llvm-symbolizer]
   34 nobody    0:00 [llvm-symbolizer]
   35 nobody    0:00 [llvm-symbolizer]
   36 nobody    0:00 [llvm-symbolizer]
   37 nobody    0:00 [llvm-symbolizer]
   38 nobody    0:00 [llvm-symbolizer]
   39 nobody    0:00 [llvm-symbolizer]
   40 nobody    0:00 [llvm-symbolizer]
   41 nobody    0:00 [llvm-symbolizer]
```

Also, parca memory usage is quite high, after only 2 hours running, the rss memory usage reached up to 12G+

[EDIT] No  IO high usage observed

I am running parca on a kernel 5.13.2 with cgroup v1

**Comment by brancz** [comment]
@kakkoyun it feels like https://github.com/parca-dev/parca/issues/213 is in order

**Comment by zq-david-wang** [comment]
Those zombies would eventually exhaust  system pid/memory resource. Hope this issue would be taken with  higher priority.

BTW, very great and helpful cool tool~!
