### ISSUE TITLE
Top Table should show Diffs for Flat and Cumulative values

### ISSUE THREAD

**Issue by metalmatze** [parca-dev/parca#2776]
The top table should show diff values for both flat and cumulative values. 
Currently, it only shows the cumulative diff, if I understand it correctly. 

![top-diff](https://user-images.githubusercontent.com/872251/225407481-1e4f65fb-1e49-4372-bfce-60904f80d7d5.png)

**Comment by yomete** [comment]
Currently, only the `cumulative`, `flat`, and `diff` values are returned from the TopTable response, do we need to do any other thing to see the value for flat diff?

<img width="898" alt="image" src="https://user-images.githubusercontent.com/9016992/233047874-30fb97ff-ae10-4074-a572-e313dfa1ea83.png">

**Comment by metalmatze** [comment]
I think we need to indeed calculate the flat diff on the backend first. Sorry, the chosen labels might have been not the best.

https://github.com/parca-dev/parca/blob/59106a3d04b5a105cceef6e24269e68c01347ea5/pkg/query/top.go#L42-L67

We should probably update the internal structs to have:
```diff
// TopNode is a node entry in a top list
message TopNode {
  // meta is the metadata about the node
  TopNodeMeta meta = 1;

  // cumulative is the cumulative value of the node
  int64 cumulative = 2;

  // flat is the flat value of the node
  int64 flat = 3;

  // diff is the diff value between two profiles
  int64 diff = 4;
+
+  // flat_diff is the diff value between two profiles if both have flat values and how they compare
+  int64 flat_diff = 5;
}
```
In a perfect world I would rename the `diff` field to `cumulative_diff` to be more explicit.

**Comment by brancz** [comment]
Done!
