### ISSUE TITLE
Add a user agent to the debuginfod client

### ISSUE THREAD

**Issue by Foxboron** [parca-dev/parca#2914]
Some distros are being spammed by a generic `Go-http-client/2` User Agent towards their debuginfod servers.

I don't know if it's this project, but I can't seem to see any User-Agent defined in this project anyway so it would be nice to have.

**Comment by kakkoyun** [comment]
@Foxboron Thanks a lot for reporting it. We will be sure to add it. I'm very sorry in advance if it's our client that causes the problem. We will take some preventive measures.

**Comment by brancz** [comment]
Opened #2924 to set the user-agent.

**Comment by Foxboron** [comment]
>But ultimately Polar Signals will also host a caching proxy to worst case spam the Polar Signals debuginfod server instead of the upstream ones.

Am I to understand this comment as it is actually an instance of parca running on GCP from Polar Signal that is causing this?

**Comment by Foxboron** [comment]
I'm happy to confirm it is in fact this project spamming our debuginfod servers :)

I'm seeing 2-3 requests pr second from this single User-Agent.

**Comment by brancz** [comment]
By “this”, you mean which user agent? (Polar Signals doesn’t run parca servers directly it uses parca code to build a horizontally scalable multi tenant version; we also configured a different user agent in polar signals now to be able to see the difference)

**Comment by Foxboron** [comment]
Sorry for the slow reply.

The user-agent is `polarsignals.com/debuginfodclient/v1` and it is still spamming Arch server. Maybe a little less then before, but still fairly often.

**Comment by brancz** [comment]
Thanks for reporting! I opened https://github.com/parca-dev/parca/issues/3028 to track further improvements.
