### ISSUE TITLE
Profile View not updating when timeframe is unchanged

### ISSUE THREAD

**Issue by brancz** [parca-dev/parca#3182]
When selecting an exact time range and then updating the query selector, the metrics graph changes, but the profile view doesn't. Only after a full refresh of the page can one see the change.

**Comment by manojVivek** [comment]
This is probably because of the front-end query data caching. The params are the cache key and since they don't change, we tend to use the data from the cache, I guess. 
I'll see what can be done about this.

**Comment by manojVivek** [comment]
Just noticed the PR #3183. Did that fix this issue?
