### ISSUE TITLE
Increase Profile Types drop down

### ISSUE THREAD

**Issue by metalmatze** [parca-dev/parca#3212]
On our new https://demo.parca.dev/devel that always runs the latest version, we ingest all sorts of profile types (12 to be exact) and the dropdown is rather small compared to my overall height of the screen.

Currently, we use the `max-h-72` class to limit its height. 
Maybe we can use something like `max-height: 50vh`  and it might grow quite a bit bigger on most screens. 

Given that the value is never used elsewhere we can use the [arbitrary values](https://tailwindcss.com/docs/max-height#arbitrary-values) helpers, like so `max-h-[50vh]`.
https://github.com/parca-dev/parca/blob/5d0edf2e2029cad81ad4a69a19e1bd6fbc1b1be8/ui/packages/shared/components/src/Select/index.tsx#L100

### Current: `max-h-72`
![max-h-72](https://github.com/parca-dev/parca/assets/872251/929c7ae5-c950-4a52-aae9-f409b5b1c961)

### New: `max-h-[50vh]`
![max-h- 50vh](https://github.com/parca-dev/parca/assets/872251/7bf34b11-3207-44b5-9e17-e163791921e0)

**Comment by themohammadsa** [comment]
hey @metalmatze ! happy to pick this up. can you assign this to me?
