### ISSUE TITLE
Usage confusion

### ISSUE THREAD

**Issue by yquansah** [parca-dev/parca#338]
So it looks like by default, Parca scrapes from it's own pprof endpoints. Does this mean if I want continuous profiling of another application, that I would have to point towards the pprof endpoints on the separate application in the parca.yaml?

(Sorry if this is an obvious answer, as it was a bit non-obvious in the documentation.)

**Comment by kakkoyun** [comment]
Hello @yquansah, thanks for reaching out. 

There are two ways to do this: the first one is using a pull-based approach, as you already described; and the second one is to use the parca-agent to push profiles from an installed machine. So if you want to use a pull-based approach you need to add a scrape config for your application.

https://www.parca.dev/docs/ingestion

Please let us know how we can improve our documentation.

**Comment by brancz** [comment]
@yquansah do you have a suggestion of what we could do to make this clearer in our documentation? Maybe we should call this out more explicitly elsewhere?

**Comment by kakkoyun** [comment]
@benmathews Thanks for the suggestion, I have added and issue for it now https://github.com/parca-dev/docs/issues/137
