### ISSUE TITLE
Don't let hover bubble overflow

### ISSUE THREAD

**Issue by brancz** [parca-dev/parca#3465]
When hovering over a line and a process has lots of labels it happens that the hover bubble wants to go beyond the height available, which causes a second scrollbar to appear and quickly disappear if one is moving the cursor to the next line. This causes a pretty disruptive jumping behavior. We should limit the height of the hover bubble to always end at the screen and instead have a scrollbar in the hover bubble instead (probably even just for the label section).

https://github.com/parca-dev/parca/assets/4546722/7746d946-8ca5-4316-a62b-20c9d2a799cc

**Comment by yomete** [comment]
I can't seem to recreate this. It was possibly fixed with the new design. 

Let me know if it still persists and I can spend some time on it again.
