### ISSUE TITLE
Add version information to Parca UI

### ISSUE THREAD

**Issue by kakkoyun** [parca-dev/parca#358]
It would be nice to see which version in the UI

**Comment by fpuc** [comment]
An idea from Discord:

 Add a struct or map in go-code
- Use this fields/keys inside the js via go template variables e.g. {{.BasePath}}, {{.Version}}
- Add a wrapper for templates near fallbackNotFound(mux, http.FileServer(http.FS(uiFS))
- version and friends are already patched in to main.go via goreleaser
- adding also a `parca --version` command

(This may also be an approach to target https://github.com/parca-dev/parca/issues/434 if this `publicRuntimeConfig.basePath = '{{.BasePath}}` helps via next.js)

The benefit of this dance is, that adding another variable to js would be copy, pasta. What

**Comment by brancz** [comment]
Closed by #467 

Thank you so much @fpuc!
