### ISSUE TITLE
UI: Don't scroll the table header

### ISSUE THREAD

**Issue by metalmatze** [parca-dev/parca#3688]
In the table visualization, the table header scrolls with the content. 
Eventually, you might be so far down in the data, that it takes super long to scroll up to the table header again (to either read it or change the sorting).

We should make sure to only scroll the table body and never the table header. 

![brave_screenshot_local polarsignals com](https://github.com/parca-dev/parca/assets/872251/0c100abd-033b-4865-91a6-09bc5f62a418)

**Comment by karthick3018** [comment]
@metalmatze I can take this

**Comment by manojVivek** [comment]
Hi @karthick3018, please go ahead, let us know if you have any questions.

**Comment by karthick3018** [comment]
@manojVivek I guess you forgot one contributer in the list

**Comment by manojVivek** [comment]
Sorry about that, thanks for the reminder! 😅

**Comment by manojVivek** [comment]
@all-contributors Please add @karthick3018 for code.
