### ISSUE TITLE
compare memery panic

### ISSUE THREAD

**Issue by guojun08512** [parca-dev/parca#3784]
panic: runtime error: index out of range [0] with length 0
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x48bc076]

goroutine 4949 [running]:
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End.func1()
	/root/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.17.0/trace/span.go:383 +0x2e
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End(0xc010141500, {0x0, 0x0, 0x0})
	/root/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.17.0/trace/span.go:421 +0xa65
panic({0x50d3b80?, 0x8fb1670?})
	/snap/go/10319/src/runtime/panic.go:920 +0x290
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End.func1()
	/root/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.17.0/trace/span.go:383 +0x2e
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End(0xc00fbed080, {0x0, 0x0, 0x0})
	/root/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.17.0/trace/span.go:421 +0xa65
panic({0x50d3b80?, 0x8fb1670?})
	/snap/go/10319/src/runtime/panic.go:920 +0x290
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End.func1()
	/root/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.17.0/trace/span.go:383 +0x2e
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End(0xc00fbed800, {0x0, 0x0, 0x0})
	/root/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.17.0/trace/span.go:421 +0xa65
panic({0x50d3b80?, 0x8fb1670?})
	/snap/go/10319/src/runtime/panic.go:920 +0x290
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End.func1()
	/root/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.17.0/trace/span.go:383 +0x2e
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End(0xc00fbed980, {0x0, 0x0, 0x0})
	/root/go/pkg/mod/go.opentelemetry.io/otel/sdk@v1.17.0/trace/span.go:421 +0xa65
panic({0x50d3b80?, 0x8fb1670?})
	/snap/go/10319/src/runtime/panic.go:920 +0x290
github.com/parca-dev/parca/pkg/query.(*flamegraphBuilder).Release(0xc00e70ca00)
	/home/zksd_asw/zksd/parca/pkg/query/flamegraph_arrow.go:981 +0x256
panic({0x55e69e0?, 0xc012c4ed08?})
	/snap/go/10319/src/runtime/panic.go:920 +0x290
github.com/apache/arrow/go/v14/arrow/array.(*Int32).Value(0xc019442240, 0x0)
	/root/go/pkg/mod/github.com/apache/arrow/go/v14@v14.0.0-20230903081620-3b14c740c71d/arrow/array/numeric.gen.go:335 +0x4a
github.com/parca-dev/parca/pkg/query.(*flamegraphBuilder).appendRow(0xc00e70ca00, 0xc00b7822d0, 0xc00e70ac40, {0xc006c984b0, 0x1, 0x1}, 0x0, 0x6, 0x6, 0x1, ...)
	/home/zksd_asw/zksd/parca/pkg/query/flamegraph_arrow.go:1016 +0x19a
github.com/parca-dev/parca/pkg/query.generateFlamegraphArrowRecord({0x6f5e038, 0xc00e7cfcb0}, {0x6f4ae20, 0x903cf80}, {0x6f2a000, 0xc006d07340}, {{0xc00124b9a0, 0x1, 0x1}, {{0xc007abc2a0, ...}, ...}}, ...)
	/home/zksd_asw/zksd/parca/pkg/query/flamegraph_arrow.go:293 +0x2b16
github.com/parca-dev/parca/pkg/query.GenerateFlamegraphArrow({0x6f5e038, 0xc00e7cfc80}, {0x6f4ae20, 0x903cf80}, {0x6f2a000, 0xc006d07340}, {{0xc00124b9a0, 0x1, 0x1}, {{0xc007abc2a0, ...}, ...}}, ...)
	/home/zksd_asw/zksd/parca/pkg/query/flamegraph_arrow.go:71 +0x2a8
github.com/parca-dev/parca/pkg/query.RenderReport({0x6f5e038, 0xc00e7cfc50}, {0x6f2a000, 0xc006d07340}, {{0xc00124b9a0, 0x1, 0x1}, {{0xc007abc2a0, 0xb}, {{0xc007abc2ba, ...}, ...}, ...}}, ...)
	/home/zksd_asw/zksd/parca/pkg/query/columnquery.go:532 +0x2fc7
github.com/parca-dev/parca/pkg/query.(*ColumnQueryAPI).renderReport(0xc006d1db20, {0x6f5e038, 0xc010d2c5d0}, {{0xc00124b9a0, 0x1, 0x1}, {{0xc007abc2a0, 0xb}, {{0xc007abc2ba, 0x3}, ...}, ...}}, ...)
	/home/zksd_asw/zksd/parca/pkg/query/columnquery.go:445 +0x254
github.com/parca-dev/parca/pkg/query.(*ColumnQueryAPI).Query(0xc006d1db20, {0x6f5e038, 0xc010d2c5d0}, 0xc016afe070)
	/home/zksd_asw/zksd/parca/pkg/query/columnquery.go:245 +0x1045
github.com/parca-dev/parca/gen/proto/go/parca/query/v1alpha1._QueryService_Query_Handler.func1({0x6f5e038, 0xc010d2c5d0}, {0x581efa0, 0xc016afe070})
	/home/zksd_asw/zksd/parca/gen/proto/go/parca/query/v1alpha1/query_vtproto.pb.go:218 +0xf2
github.com/grpc-ecosystem/go-grpc-middleware/v2/interceptors.UnaryServerInterceptor.func1({0x6f5e038, 0xc010d2c4b0}, {0x581efa0, 0xc016afe070}, 0xc0178c4120, 0xc00a84a0d8)
	/root/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware/v2@v2.0.0/interceptors/server.go:22 +0x368
google.golang.org/grpc.getChainUnaryHandler.func1({0x6f5e038, 0xc010d2c4b0}, {0x581efa0, 0xc016afe070})
	/root/go/pkg/mod/google.golang.org/grpc@v1.57.0/server.go:1179 +0x126
github.com/grpc-ecosystem/go-grpc-middleware/v2/interceptors.UnaryServerInterceptor.func1({0x6f5e038, 0xc010d2c4b0}, {0x581efa0, 0xc016afe070}, 0xc0178c4120, 0xc016574600)
	/root/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware/v2@v2.0.0/interceptors/server.go:22 +0x368
google.golang.org/grpc.getChainUnaryHandler.func1({0x6f5e038, 0xc010d2c4b0}, {0x581efa0, 0xc016afe070})
	/root/go/pkg/mod/google.golang.org/grpc@v1.57.0/server.go:1179 +0x126
go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc.UnaryServerInterceptor.func1({0x6f5e038, 0xc010d2c4b0}, {0x581efa0, 0xc016afe070}, 0xc0178c4120, 0xc0165744c0)
	/root/go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc@v0.43.0/interceptor.go:376 +0xaf9
google.golang.org/grpc.chainUnaryInterceptors.func1({0x6f5e038, 0xc010d2c3c0}, {0x581efa0, 0xc016afe070}, 0xc0178c4120, 0xc00a84a0d8)
	/root/go/pkg/mod/google.golang.org/grpc@v1.57.0/server.go:1170 +0x10d
github.com/parca-dev/parca/gen/proto/go/parca/query/v1alpha1._QueryService_Query_Handler({0x57394a0, 0xc006d1db20}, {0x6f5e038, 0xc010d2c3c0}, 0xc016afe000, 0xc006d0f640)
	/home/zksd_asw/zksd/parca/gen/proto/go/parca/query/v1alpha1/query_vtproto.pb.go:220 +0x216
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000dc21e0, {0x6f70fa0, 0xc00c630000}, 0xc007afa000, 0xc006c824e0, 0x8fcded8, 0x0)
	/root/go/pkg/mod/google.golang.org/grpc@v1.57.0/server.go:1360 +0x1707
google.golang.org/grpc.(*Server).handleStream(0xc000dc21e0, {0x6f70fa0, 0xc00c630000}, 0xc007afa000, 0x0)
	/root/go/pkg/mod/google.golang.org/grpc@v1.57.0/server.go:1737 +0x88a
google.golang.org/grpc.(*Server).serveStreams.func1.1()
	/root/go/pkg/mod/google.golang.org/grpc@v1.57.0/server.go:982 +0xfd
created by google.golang.org/grpc.(*Server).serveStreams.func1 in goroutine 4946
	/root/go/pkg/mod/google.golang.org/grpc@v1.57.0/server.go:980 +0x237

**Comment by brancz** [comment]
I believe we've just run into the same panic. @metalmatze is on it.
