### ISSUE TITLE
Convert time in "Process CPU nanoseconds" to human-readable value

### ISSUE THREAD

**Issue by rlex** [parca-dev/parca#382]
As discussed in discord https://discord.com/channels/877547706334199818/877547706334199821/902870834459344946

Convert it to human-readable time instead of G

<img width="557" alt="Screenshot 2021-10-27 at 13 43 16" src="https://user-images.githubusercontent.com/84462/139055701-9230046c-da26-434e-9f5e-d47ed99fe3fc.png">

Maybe also convert ones in icicle graph?

**Comment by yeya24** [comment]
Is there a way to get the value unit from the `query_range` API? If not, then maybe we can extend the query range response with the unit?

**Comment by brancz** [comment]
There is not today, but that's a great idea! Do you want to give it a try @yeya24 ?

**Comment by metalmatze** [comment]
Just to be clear: You want to propagate the profile `ValueType.Unit` to the UI, right? Like `seconds, nanoseconds, bytes`? Sounds good! :100:

**Comment by brancz** [comment]
Actually, both the entire PeriodType and ValueType would be useful, not just the unit (as then we could even calculate CPU core seconds from CPU sample profiles/metrics).
