### ISSUE TITLE
Add percentage to table

### ISSUE THREAD

**Issue by brancz** [parca-dev/parca#3880]
While we have the table "visualization" for profiling data, it currently only shows the static value. It would be very useful to understand at glance how much in relation to the whole that is, so show the percentage as well. I think we could just show that inline with the value.

<img width="1829" alt="Screenshot 2023-09-26 at 13 26 32" src="https://github.com/parca-dev/parca/assets/4546722/f877b4b4-8a17-4bd2-a84a-86c4bc318dba">

**Comment by metalmatze** [comment]
This has been implemented.
