### ISSUE TITLE
Bucket configuration options

### ISSUE THREAD

**Issue by wbollock** [parca-dev/parca#3929]
Hello! I'm a bit confused on the options for the `bucket:` configuration YAML section. I can't find much documented anywhere, and code references only point to using GCS:

* https://github.com/parca-dev/parca/blob/d2b3947b351823a13da1b29757b4c8901e70e90c/pkg/signedrequests/gcs.go#L31-L34
* https://github.com/parca-dev/parca/issues/3048

Are other bucket providers supported/PRs welcome? It would be nice to support any S3 compatible object storage option

Edit: does seem that GCS is the only supported provider - https://github.com/parca-dev/parca/blob/d2b3947b351823a13da1b29757b4c8901e70e90c/pkg/signedrequests/client.go#L34-L36

I'd love to add a option for Linode OBJ/generic S3 if welcome

**Comment by brancz** [comment]
That's just for using signed requests. We reuse the Thanos configuration, so the relevant S3 documentation is here: https://thanos.io/tip/thanos/storage.md/#s3

**Comment by wbollock** [comment]
ah thank you! took me a while to realize that the scrape configuration was literally all the options Prometheus had, awesome to see it's the same for thanos

**Comment by thorfour** [comment]
Closing as this appears to be resolved. Please feel free to open again @wbollock if your questions aren't resolved.
