### ISSUE TITLE
Closing quote not being autocompleted

### ISSUE THREAD

**Issue by brancz** [parca-dev/parca#4023]
Several users have reported that they expected the closing quote to be auto-completed and the cursor to be between the two quotes when either typing the opening quote or selecting a matcher type definitively (eg. just typing `=` is not definitive, but if it's selected explicitly it is, whereas when having typed `!=`, `=~` or `!~` or selected it it's definitely "done".

**Comment by manojVivek** [comment]
This PR addresses this, but not by keeping the cursor in-between the quotes, but by auto-appending the quotes on selection of an appropriate suggestion: https://github.com/parca-dev/parca/pull/4155

**Comment by manojVivek** [comment]
I guess, we can close this as the behaviour in the PR is solving the problem.
