### ISSUE TITLE
Make relative time picker linear

### ISSUE THREAD

**Issue by brancz** [parca-dev/parca#4024]
We've had user feedback saying that the two-column time picker is confusing as a they read in the order of an academic paper, which is unexpected.

<img width="310" alt="Screenshot 2023-10-31 at 16 18 56" src="https://github.com/parca-dev/parca/assets/4546722/8c84d8ec-444c-4fa8-a5c3-aff839fde1f3">

Maybe we should try a single column approach?

**Comment by monicawoj** [comment]
@brancz by "columns" do you mean that instead of two columns for the "Last 15 min" "Last 1 hour" etc. options we should have them in a single column?

**Comment by brancz** [comment]
Right now we have 

Last 15min | Last 6 hours
Last 1 hour | Last 12 hours
Last 3 hours | Last 1 day

We should just make it

Last 15min
Last 1 hour
Last 3 hours
Last 6 hours
Last 12 hours
Last 1 day

And as I was writing this, I think that means we basically want it to be like the other dropdowns we have except for the ability to somehow adjust the lookback and absolute times.

**Comment by monicawoj** [comment]
Hmm, I feel like that might significantly extend the vertical space/height of the time range selector. Is it at all necessary to have the "Last 15 min" "Last 1 hour" etc. options explicitly displayed given that the "Last <number input> <unit dropdown>" component covers all of those cases and more? We could save what the user last chose as the number input and unit in cache so that they wouldn't have to edit this every time if they usually use the same relative time range?

**Comment by brancz** [comment]
Maybe it’s worth looking at what prometheus does? I quite like that experience. -/+ buttons on both ends of the button to increase/decrease and a click on the “text” reveals the menu to write it out or select absolutes?

**Comment by kakkoyun** [comment]
Could we have a slider maybe? With predefined points in time.

**Comment by asubiotto** [comment]
Grafana approach for reference:
![image](https://github.com/parca-dev/parca/assets/10560359/f248c08b-f1e0-4cd6-8929-1a894963071d)

**Comment by monicawoj** [comment]
Oh I like in the Grafana approach that the predefined "quick ranges" are hidden within a search! It's mainly the vertical space that I was hesitant about by converting our current solution to a single column.

**Comment by brancz** [comment]
Not sure the search makes any sense to me and I personally find Grafana’s picker way too busy.
