### ISSUE TITLE
cross compiling for ARM support

### ISSUE THREAD

**Issue by Jiahao0** [parca-dev/parca#4060]
Hi, the project looks very powerful. I would like to try parca on ARM64 embedded environement. Is there a release pkg for ARM64? If not, does it support cross compiling for ARM64 target?

Thanks.

**Comment by kakkoyun** [comment]
Hey 👋 We have releases for ARM64. Please check out the assets of the releases https://github.com/parca-dev/parca/releases/tag/v0.20.0

Let us know how your journey goes and how we can be helpful
