### ISSUE TITLE
Special characters in search bar get lost when changing UI settings

### ISSUE THREAD

**Issue by fpetkovski** [parca-dev/parca#4158]
I typically use the UI to search using regex matchers as in `pod=~"querier.+"`. When this state is present in the search bar and I change sorting or grouping options for selected profiles, the `.+` gets replaced by `. ` and I lose my search results.

**Comment by brancz** [comment]
I suspect this is a bug in the way the query is maintained in the URL.

cc @manojVivek @yomete @monicawoj
