### ISSUE TITLE
bug: debuginfod logger never inited

### ISSUE THREAD

**Issue by dreamerlzl** [parca-dev/parca#4262]
As pointed out in https://github.com/parca-dev/parca/issues/3978, the field `logger` under `DebuginfodClientObjectStorageCache` is never initialized (it's an interface nil).

**Comment by metalmatze** [comment]
You're right!
At least a `log.NewNopLogger()` should be initialized in the constructor. Furthermore, we should pass the logger into the constructor, as it constantly logs to nowhere. 

Given there's only one usage for logging in this code path, it wasn't often hit, but it should be fixed regardless!
Do you want to send a PR?

**Comment by dreamerlzl** [comment]
> You're right! At least a `log.NewNopLogger()` should be initialized in the constructor. Furthermore, we should pass the logger into the constructor, as it constantly logs to nowhere.
> 
> Given there's only one usage for logging in this code path, it wasn't often hit, but it should be fixed regardless! Do you want to send a PR?

Ok, I will send a PR soon.
