### ISSUE TITLE
Tutorial for deploying parca isn't working - Parca agent keeps crashing

### ISSUE THREAD

**Issue by Adib234** [parca-dev/parca#4603]
Hello, I'm following this tutorial https://www.parca.dev/docs/kubernetes/ and everytime I try to provision the Parca agent as a DaemonSet, the agent always has a status of CrashLoopBackOff after verifying it with `kubectl get pods -n parca`

```
adibakm@adib9 ~> kubectl get pods -n parca
NAME                    READY   STATUS             RESTARTS      AGE
parca-agent-ntnxq       0/1     CrashLoopBackOff   6 (43s ago)   6m24s
parca-fbb56f99f-lw4tr   1/1     Running            0             14m
```

**Comment by brancz** [comment]
How did you create this Kubernetes cluster? Which kernel version is this on?

**Comment by Adib234** [comment]
I used the tool kind https://kind.sigs.k8s.io/ to create the cluster. How would I identify the kernel version?

**Comment by brancz** [comment]
![IMG_0920](https://github.com/parca-dev/parca/assets/4546722/e160c388-a71e-41f9-bd95-c1e6fa014d0b)

As the guide says, can you try again with a real VM, like with minikube? The problem is that kind uses user-namespaces, which prevent the agent from correctly observing and working with the Kernel.

**Comment by Adib234** [comment]
I tried this with a real VM and it works now, thank you!
