### ISSUE TITLE
Improved diff icicle-graph coloring

### ISSUE THREAD

**Issue by brancz** [parca-dev/parca#463]
1) It tends to be separately interesting if stacks are entirely new in icicle-graphs as opposed to having gotten worse/better currently denoted with green/red.
2) Measurements that are only very slightly different in contrast to the cumulative root diff, should probably still be colored in a variation of blue rather than green/red.
3) A legend for coloring would be great, as it's quite hard to grasp right now what the different colors mean.

**Comment by yomete** [comment]
When stacks are new as mentioned in the first point, should they be represented with blue or some other new color entirely?
