### ISSUE TITLE
Versioned metastore keys

### ISSUE THREAD

**Issue by brancz** [parca-dev/parca#464]
@kakkoyun correctly mentioned that it's possible that our understanding of what makes a record unique might change over time, so our keys for locations, functions and mappins should be verioned. Eg. these prefixes should contain a `v1` versioned string somewhere: 

https://github.com/parca-dev/parca/blob/c086e4d35270f1fd0903f93f0842f3d8737e7131/pkg/storage/metastore/kv.go#L22

**Comment by cbrgm** [comment]
Merged in #484  🎉

**Comment by brancz** [comment]
Thank you very much @cbrgm! :tada:
