### ISSUE TITLE
Make builds more reproducible by deleting build time

### ISSUE THREAD

**Issue by metalmatze** [parca-dev/parca#468]
Right now we have the strings `date` and `builtBy` as part of building the Parca binary. 
Especially `date` isn't good for reproducible builds. We should simply get rid of it. 
Additionally, I'm not sure if `builtBy` is actually helpful for most cases since our CI is going to build the releases.

I'd say, let's get rid of this:
https://github.com/parca-dev/parca/blob/4a828ea71340fb3fff3e21e86fe74657348929fc/cmd/parca/main.go#L31-L32

**Comment by brancz** [comment]
Agreed, we put so much work into reproducibility for Parca Agent, let's make sure we put the same care into Parca.

**Comment by metalmatze** [comment]
This should have been closed by #467
