### ISSUE TITLE
fgprof UI Integration

### ISSUE THREAD

**Issue by syepes** [parca-dev/parca#472]
It would be great if the fgprof profiles would be natively supported, when scraping these types of profiles they look a bit messy n the UI.

<img width="547" alt="image" src="https://user-images.githubusercontent.com/333081/143835007-689eb466-ab47-4481-b7a5-ba4b9a530d8a.png">

**Comment by brancz** [comment]
Agreed! This would be great! Well known profile types are defined here: https://github.com/parca-dev/parca/blob/850f0cf06b71552c472d9c580994496bab34d711/ui/packages/app/web/src/components/ProfileSelector.tsx#L70-L123

Would love a contribution if you want to give this a try!

**Comment by yomete** [comment]
Hey @syepes is this something you are still interested as a contribution?
