### ISSUE TITLE
Label value autocompletion in UI

### ISSUE THREAD

**Issue by brancz** [parca-dev/parca#473]
The backend is already capable of returning label values for a given label name, but the UI is not currently using it to suggest it in autocompletion. This would be great in order to explore the data through suggestions.

**Comment by yomete** [comment]
@brancz afaik, these are the possible labels we can have autocompletion for, lmk if i missed any or remove from the list as this is what I'm going to implement.

- `instance`
- `__address__`
- `__name__`
- `__profile_path__`
- `__scheme__`
- `job`

**Comment by metalmatze** [comment]
There are two API calls that are made. 
First, we get all the names (which is basically the list that you posted) by calling `/api/parca.query.v1alpha1.QueryService/Labels` and then we can request all values for the given names by calling `/api/parca.query.v1alpha1.QueryService/Values`. The second call has a payload that by default requests all `__name__` values, but can be changed to whatever label name we need to auto complete.

**Comment by yomete** [comment]
I see. thanks for explaining! I thought we had a fixed list but knowing it's all from an API makes it better
