### ISSUE TITLE
ui: assets URLs no longer using path prefix

### ISSUE THREAD

**Issue by maxbrunet** [parca-dev/parca#4827]
E.g. https://demo.parca.dev/devel/, path prefix is set to `/devel/`, but assets point to:

* `/assets/index-B7BUVs7v.js`
* `/assets/index-CMIgWbWG.css`

My hunch would be toward #4796 as the cause, but I have not investigated.

**Comment by manojVivek** [comment]
Max, thanks for reporting. 
Yes, you're right about the cause. 

Fixed by #4832
