### ISSUE TITLE
Add custom time ranges to the UI 

### ISSUE THREAD

**Issue by metalmatze** [parca-dev/parca#483]
Right now we can only select for data in the last 14d, 7d, 3d, 1d, 1h. 
Maybe we can figure out a way in the dropdown (or next to the dropdown) to take custom ranges like 6h or 8h.

**Comment by manojVivek** [comment]
@metalmatze Shouldn't we also be allowing absolute time ranges? 

We could switch to a `Super Date Picker` component like in Kibana to support both relative and absolute ranges?

**Comment by brancz** [comment]
Super date picker looks great! I didn't know about it, I'm happy with using something like that.

**Comment by manojVivek** [comment]
Is it OK if we use a library that is under [`Elastic License 2.0`](https://github.com/elastic/eui/blob/main/LICENSE.txt)? 🤔

**Comment by yomete** [comment]
I've used this [react-datepicker](https://www.npmjs.com/package/react-datepicker) a couple of times and it also supports time ranges 👌🏾

**Comment by brancz** [comment]
We cannot use the elastic license, it's not compatible with apache 2.

**Comment by manojVivek** [comment]
> I've used this [react-datepicker](https://www.npmjs.com/package/react-datepicker) a couple of times and it also supports time ranges 👌🏾

Yeah, `react-datepicker` looks cool, except that it doesn't have support relative ranges from current time like `last 1 hour`. 
I'll search for alternatives and if nothing is good, will try to modify `react-datepicker` a bit to include it.

**Comment by manojVivek** [comment]
I found a couple of similar ones but not quite suitable for us:
1. https://github.com/dangrossman/daterangepicker: Good in functionality, but jQuery based.
2. https://github.com/Dishant15/react-datetime-range-super-picker: React based, but UI is not great and not much community usage.

I'll create a custom time range picker component making use of `react-datepicker` with relative time range support.

**Comment by brancz** [comment]
Seems like the right option!

**Comment by manojVivek** [comment]
@brancz Can you please close this issue, I missed linking it to the PR.
