### ISSUE TITLE
Flaky test `Test_QueryRange_Limited`

### ISSUE THREAD

**Issue by brancz** [parca-dev/parca#499]
I've noticed the `Test_QueryRange_Limited` test flakes every now and then on PRs. This should be fixed.

**Comment by metalmatze** [comment]
I was trying to find a flaky test log output on GitHub Actions. Is there still some available? I wasn't able to find anything under Go in our Github Actions.
Could you link to one? Thanks.

**Comment by brancz** [comment]
https://github.com/parca-dev/parca/runs/4507396630?check_suite_focus=true

**Comment by brancz** [comment]
https://github.com/parca-dev/parca/runs/4591987969?check_suite_focus=true

**Comment by metalmatze** [comment]
Thanks for the links. Something is up with this test. While working on the deletion of profile trees it got my attention because it took 30s to complete. I'll definitely take a closer look on what's going on.

**Comment by metalmatze** [comment]
Still flaky...

**Comment by importhuman** [comment]
Think this can be closed as #771 is closed

**Comment by metalmatze** [comment]
Nice. Yes, if it ever shows up again let's open a new one.
