### ISSUE TITLE
parca-server 0.6.0 shows dev in the UI

### ISSUE THREAD

**Issue by gerhard** [parca-dev/parca#502]
`ghcr.io/parca-dev/parca:v0.6.0` image is showing `dev` in the UI:

![image](https://user-images.githubusercontent.com/3342/146513673-74e64bd1-616f-4fd2-b891-7c3aa9b3f44a.png)

re https://github.com/thechangelog/changelog.com/pull/396

**Comment by fpuc** [comment]
Just verified, that this is not only the UI: This is also true for logs and --version call:

```
level=debug name=parca ts=2021-12-17T09:45:37.143174732Z caller=main.go:48 msg="parca initialized" version=dev commit=dev config="&{parca.yaml debug :7070 []  false 6h0m0s false false simple 3 badgerinmemory}"
```

```
parca --version
parca, version dev (commit: dev)
```

**Comment by fpuc** [comment]
```    
    ...
    ldflags:
      - main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser````

**Comment by fpuc** [comment]
```    flags:
      - -trimpath
      - -v
    ldflags:
      - main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser
 ```

We may need to add `-X` before the `main.version`

https://goreleaser.com/customization/build/ says:

```
# Custom ldflags templates.
    # Default is `-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser`.
```

```
-s
	Omit the symbol table and debug information.
-w
	Omit the DWARF symbol table.
```

We could also try to life with defaults IMO

**Comment by brancz** [comment]
We do not want to remove the symbol table and dwarf information, but I agree let's add the `-X` flag. Do you want to fix this one @fpuc?

**Comment by gerhard** [comment]
Just deployed `ghcr.io/parca-dev/parca:v0.6.1` and the UI is still showing `dev`:
![image](https://user-images.githubusercontent.com/3342/147136258-c9c816e5-447a-4a35-a568-f445bd6d2316.png)

Same for the binary:

```
~ $ ./parca --version
parca, version dev (commit: dev)
```

**Comment by fpuc** [comment]
Hi Gerhard, 

Thanks for reporting. The binaries of v0.6.1 have this patched in -  you are completely right - the docker image doesn't have this until now.  @metalmatze found already the issue here: https://github.com/parca-dev/parca/blob/main/Dockerfile#L44)

**Comment by metalmatze** [comment]
Just opened a PR to add VERSION and COMMIT to the containers:
https://github.com/parca-dev/parca/pull/537
