### ISSUE TITLE
Remove the grpc.WithBlock option when connecting to OTEL collector?

### ISSUE THREAD

**Issue by yeya24** [parca-dev/parca#509]
https://github.com/parca-dev/parca/blob/main/pkg/parca/parca.go#L305 parca initializes the OTEL exporter with the grpc blocking mode. This option is usually set for debugging purposes.
If the OTEL collector is down, parca should still do its job and shouldn't be blocked here.

**Comment by brancz** [comment]
Whops you're 100% right. Do you want to give try and fix it?
