### ISSUE TITLE
cgroupv2 support

### ISSUE THREAD

**Issue by mskarbek** [parca-dev/parca#522]
Hi, I would like to ask is there any work in progress for supporting cgroup v2 for systemd service discovery? 
Currently, `parca-agent` documentation states that only v1 is supported, and I can't find any specific, v2 related  issue.

**Comment by kakkoyun** [comment]
Het @mskarbek, thanks for reaching out.

We actually implemented cgroup v2 support. You can check https://github.com/parca-dev/parca-agent/issues/23 for further information.

That said, I will make sure our documentation is updated when we release a new agent version.
