### ISSUE TITLE
Flatten the flamegraph gRPC API

### ISSUE THREAD

**Issue by metalmatze** [parca-dev/parca#544]
Right now a flame graph is returned as [nested data structure](https://github.com/parca-dev/parca/blob/6b36de962cd772a92e72ccfbcbb6eae8324f7835/proto/parca/query/v1alpha1/query.proto#L204-L263) (similar to a tree).
This has both some overhead in terms of computing the tree on the server-side when querying as well as when rendering the flame graph the UI has to recursively render the tree.

We can simply flatten that data to returns something like an array.
This will allow us to improve rendering the icicle graph without recursion by instead computing the width and height of each span and its absolute offset in the canvas.

/cc @brancz

**Comment by yomete** [comment]
@metalmatze do you think this particular issue has been solved by the new flamegraph Arrow implementation?

**Comment by brancz** [comment]
yes, we can close this, it's obsolete now
