### ISSUE TITLE
Grafana data source plugin

### ISSUE THREAD

**Issue by mhausenblas** [parca-dev/parca#571]
Amongst other things, for correlation use cases it would be beneficial to use the Parca server via a [data source plugin in Grafana](https://grafana.com/grafana/plugins/).

**Comment by kakkoyun** [comment]
For inspiration https://github.com/yeya24/conprof-datasource

**Comment by manojVivek** [comment]
Here is the progress on the plugin:

- [x] Parca Panel plugin
- [x] ~~Parca Datasource plugin(frontend only)~~We need the backend data source plugin
- [ ] Parca backend datasource plugin
- [ ] Implement health check
