### ISSUE TITLE
internal/trace failure when parsing HTTP response

### ISSUE THREAD

**Issue by povilasv** [parca-dev/parca#60]
If try to parse trace profile directly from HTTP response we get this error back:
```
failed to parse target's trace profile: failed to read event 3 argument at offset 0 (failed to read trace at offset 13621: read 1, error EOF)
```

Right now the workaround is to read bytes into buffer and only then parse the profile:
```
b, err := ioutil.ReadAll(resp.Body)
if err != nil {
	return errors.Wrap(err, "failed to read body")
}
_, err = trace.Parse(io.TeeReader(bytes.NewBuffer(b), w), "")
if err != nil {
	return errors.Wrap(err, "failed to parse target's trace profile")
}
```

This is sort of blocked on https://github.com/golang/go/issues/38971 as right now the package is internal and shouldn't be called from anywhere except for Go internals.

I think we can try to work on a fix, if they expose the package.

**Comment by brancz** [comment]
For now we're only supporting pprof formatted profiles, we might come back to this in the future.
