### ISSUE TITLE
Port go's traceui to conprof

### ISSUE THREAD

**Issue by povilasv** [parca-dev/parca#61]
We would like to port Go's trace web UI to conprof.

PR started in https://github.com/conprof/conprof/pull/56

**Comment by brancz** [comment]
Until we finish this, I'm gonna go ahead and remove the trace profiles from being collected as they cause errors everywhere (RE https://github.com/conprof/conprof/pull/117).

**Comment by danielzheng** [comment]
This is a very useful feature, looking forward to having this job done soon.

**Comment by brancz** [comment]
For now we're focusing only on pprof formatted profiles.
