### ISSUE TITLE
Convert remaining usage of Moment.js to date-fns

### ISSUE THREAD

**Issue by monicawoj** [parca-dev/parca#613]
While Moment.js was replaced to date-fns throughout the code, there are still places where it being used. These include: `ProfileMetricsGraph`, `MetricsGraph`, `ProfileSelector`, `ProfileSource`, and `time.ts`.

**Comment by me-diru** [comment]
Hi, may I work on this issue? thanks!

**Comment by brancz** [comment]
you got it!
