### ISSUE TITLE
Add Parca storage-less scraper

### ISSUE THREAD

**Issue by metalmatze** [parca-dev/parca#629]
Next to having the Parca agent creating pprof profiles from eBPF and then sending it off via gRPC we should also support a mode of Parca which can scrape profiles from pprof endpoints and then immediately send them off via gRPC not having a local storage.
It's probably similar to the Prometheus agent mode.

**Comment by yeya24** [comment]
Would be great to support this feature as we want to collect profiles from multiple clusters and store those profiles at a central cluster.

**Comment by metalmatze** [comment]
It's on my roadmap for the next weeks! 
If you want to go for it in the meantime let me know.
