### ISSUE TITLE
pprof web view: Add info about what metric we are looking at,

### ISSUE THREAD

**Issue by bwplotka** [parca-dev/parca#65]
Some web page html header with this info would be nice, especially if you have so many tabs opened ;p

**Comment by metalmatze** [comment]
for sure, I found the same before where I'm not sure about the type anymore. Is it a heap, goroutines etc. :)

**Comment by bwplotka** [comment]
This one actually is on the right top corner ;p 

![image](https://user-images.githubusercontent.com/6950331/86906993-47682f80-c10c-11ea-8aff-e9eb80321da6.png)

**Comment by brancz** [comment]
yeah a lot of this has to do with how hacky the pprof UI has to be used, ideally what I would like to see is embedding these functionalities directly into the single-page-app

**Comment by brancz** [comment]
with the conprof -> parca evolution we have an entirely new web ui
