### ISSUE TITLE
Time picker uses local browser time vs UTC in graphs

### ISSUE THREAD

**Issue by metalmatze** [parca-dev/parca#663]
For now, we probably only want to support UTC across all parts of the UI. Hence, we should update the date time picker to use UTC as well. 
Threw me off when entering time in absolute after hovering the metrics.

**Comment by manojVivek** [comment]
Since we don't mention UTC explicitly anywhere, I thought it is best to keep it to local time. 

Also, should we try adding a `toggle` input to the absolute range tab, to choose between local time and UTC? Or is it an overkill at this time?

**Comment by metalmatze** [comment]
Yes, true. It's not properly documented anywhere.
Since servers, Prometheus etc are all UTC by default and especially with teams across time zones UTC just makes the most sense.

I'd say let's stick with UTC for now and we can think of a toggle in another release as a separate feature?

**Comment by brancz** [comment]
Not using UTC is extremely confusing in monitoring systems. Since we have no way of ensuring we're doing the same as another system the safest thing for us to do is use UTC I think. We should, however, be very explicit in our display saying that the time we're displaying is UTC.
