### ISSUE TITLE
symbolizer: Enable debug info store to have multiple versions of debug info files per build id

### ISSUE THREAD

**Issue by kakkoyun** [parca-dev/parca#705]
- Priorities the one we collect with agents

cc @Sylfrena @brancz

**Comment by brancz** [comment]
I was just thinking .. why would we have multiple versions at all? I expected that if debuginfos are present in debuginfod we wouldn't upload in the first place from the agent.

**Comment by kakkoyun** [comment]
True, maybe it'll be a waste of resources. I thought having much debug info possible, we can increase chances of symbolizing the stacks. I have no strong feels about it, happy to close it and keep things simple.

**Comment by brancz** [comment]
I think primarily I'd err on the side of not uploading if we don't absolutely have to because we would be uploading the same debuginfos thousands of times most likely.
