### ISSUE TITLE
Missing step(s) in CONTRIBUTING.md

### ISSUE THREAD

**Issue by importhuman** [parca-dev/parca#707]
The [getting started](https://github.com/parca-dev/parca/blob/main/CONTRIBUTING.md#getting-started) section for 

```
To profile all containers using Kubernetes, the parca-server can be run alongside parca-ui using Tilt.
```

doesn't mention the need to run `make dev/setup`. A response similar to the attached image is obtained if this step is not carried out.

![Screenshot from 2022-03-03 23-14-44](https://user-images.githubusercontent.com/69148722/156621753-86d94cdc-23a8-4d7d-b09a-d6f4c4485e8f.png)

My internet isn't working too well today so I haven't been able to complete the setup yet, will try tomorrow and update this issue if anything else is needed. 

Will also submit the required PR.

**Comment by kakkoyun** [comment]
Thanks for pointing out. We should have done a better job for the docs. In case you haven't seen, we have a couple of setup scripts https://github.com/parca-dev/parca/blob/main/env.sh, https://github.com/parca-dev/parca/blob/main/env-jsonnet.sh

Looking forward to your PR. Let us know if you need anthing.

**Comment by importhuman** [comment]
Yes, the setup scripts are run by `make dev/setup` so there's no need to mention it separately in the doc.
Rest of the setup looks good, no issues encountered.

One question I have is, the commit log looks like PRs are made from forks of the repo, but the contributing document doesn't ask to do so. Which path should I follow? Will add the fork step to the doc if that's required.

**Comment by brancz** [comment]
I think there's a bit of a mix happening. When maintainers are collaborating on a feature branch it might be pushed to the main repo, but generally speaking, development happens in forks.
