### ISSUE TITLE
Difference in tilt setup file

### ISSUE THREAD

**Issue by importhuman** [parca-dev/parca#745]
Was setting up parca locally, and noticed a diff in `deploy/tilt/parca-server-deployment.yaml` , where the following lines were added:
```
--debug-infod-upstream-servers=https://debuginfod.systemtap.org/
--debug-infod-http-request-timeout=5m
```
Is this a user/device specific change to the configuration? If not, I'm happy to raise a PR for adding it.

**Comment by brancz** [comment]
These were added recently, looks like we forgot to re-generate afterwards, please do send a patch! :)
