### ISSUE TITLE
Flaky test: `Test_QueryRange_Limited`

### ISSUE THREAD

**Issue by importhuman** [parca-dev/parca#771]
## What

The mentioned test in `pkg/query/query_test.go` sometimes fails at [L191 (at the time of this issue)](https://github.com/parca-dev/parca/blob/17240b60e9dfea852e0a8c965204244d3a39e13a/pkg/query/query_test.go#L191). This is because of a random limit calculation on [L181](https://github.com/parca-dev/parca/blob/17240b60e9dfea852e0a8c965204244d3a39e13a/pkg/query/query_test.go#L182). It calculates a random integer in the half-open interval `[0,n)`, that is, 0 can be chosen. I could not find a random positive integer function that does not include 0. 

## (Some of) The possible solutions

- Instead of using `rand.Intn(numSeries)`, we use `rand.Intn(numSeries - 1) + 1`. This keeps the upper limit the same, but the lower limit is set to 1 instead of 0.
- Wrap `rand.Intn(numSeries)` in a loop that breaks if the value > 0.

**Comment by metalmatze** [comment]
As a previous reference: https://github.com/parca-dev/parca/issues/499
Let's keep this one open since we have it now too and the other one is already closed.

**Comment by importhuman** [comment]
Do any of the solutions I mentioned sound viable? Any others you have in mind?

**Comment by metalmatze** [comment]
Yes, they sound reasonable. Feel free to try and send a PR. It'll probably be better either way! :relaxed:
