### ISSUE TITLE
Proposal: Rename current query range API to avoid confusion with Prometheus query_range

### ISSUE THREAD

**Issue by bwplotka** [parca-dev/parca#80]
The current Query Range is misleading as we plan (maybe?) to maintain Prometheus-like API structure for metadata, add remote read but allow query range with a different response format than official [query_range](https://prometheus.io/docs/prometheus/latest/querying/api/#range-queries) and no PromQL support.

It feels like even our search UI needs remote read, not Query capabilities. What do you think?  This assumes react do protobuf formatting just fine (seems so: https://medium.com/@singhandresh09/using-protobuf-in-react-native-7cc8286389f5)

**Comment by bwplotka** [comment]
This aligns with https://github.com/conprof/conprof/pull/54, @brancz do you plan to continue remote write support? (:

**Comment by brancz** [comment]
The remote read endpoint in #54 is very different from the query_range endpoint in the API (remote read extracts many series and samples from profiles, whereas query range just gets profile's timestamps; both are important).

I'm happy to have a proto API (even gRPC), but I think that's a different thing to worry about entirely. Also I don't think I want to solve anything PromQL related in conprof again, if someone wants that functionality they will need to put a Prometheus next to conprof, then profiles can be explored via Prometheus with the remote read endpoint and PromQL.

**Comment by bwplotka** [comment]
> The remote read endpoint in #54 is very different from the query_range endpoint in the API (remote read extracts many series and samples from profiles, whereas query range just gets profile's timestamps; both are important).

You are right.

To me we need then two remote read-like APIs. One (#54) has to be Prom compatible for extracting metrics, series, and second for querying (matching) what profile's timestamps and labels we have. To me second is also remote read like, but ofc I don't think it's imporant if proto or not. I only care to NOT confuse with Prometheus query range.

Ok to me then we just need to rename it... WDYT?

**Comment by brancz** [comment]
I'm happy with finding a different name, although it reflects what it's doing pretty well I think.

**Comment by brancz** [comment]
with the conprof -> parca re-brand we now have an entirely new gRPC API, where query range is identical to the Prometheus one
