### ISSUE TITLE
Enrich pprof view by i-framing it within React App

### ISSUE THREAD

**Issue by bwplotka** [parca-dev/parca#82]
I think the best way to keep consistent (and maintained) Go pprof UI AND add additional context and options, I would create another page with embedded directly pprof UI. This way we can have both worlds: maintainability and customizations.

The alternative is to... create our own profiles UI. I think this will be amazing long term to support more languages (Rust, Java etc), but not for now. I-framing will also mean that swapping UI will be easy.

WDYT?

**Comment by brancz** [comment]
Can you explain how this would be different from today? The current pprof UI endpoints could already be embedded via i-frames. (we just need to actually do it :) )

**Comment by bwplotka** [comment]
The difference is that we can enrich it and give full context, for example:

![image](https://user-images.githubusercontent.com/6950331/94677223-76113300-0314-11eb-9c79-3294ff22ec9e.png)

Link to edit this if someone wants to play with it: https://excalidraw.com/#json=4810715584004096,xkg_datuQNbzLkUlVpPTyA

**Comment by brancz** [comment]
I misunderstood, yes I think this would be useful. I guess what I was saying is that it's already embeddable, so this should be a relatively quick win.

**Comment by brancz** [comment]
with the conprof -> parca re-brand we now have an entirely new web UI where this and more is possible
