### ISSUE TITLE
Units are not returned properly by columnstore

### ISSUE THREAD

**Issue by roidelapluie** [parca-dev/parca#940]
The legend in 092eabc2 with columnstore is not correct (00000 is displayed):

![legend_001](https://user-images.githubusercontent.com/291750/163147933-1725a3f0-37ef-4e32-b19a-1a0b3a4ea5be.png)

Using inspect I notice that the value is e.g. "8000000000.0", so we are probably just not doing the units anymore.
The same is true for the tooltip, we have the raw number without unit.

**Comment by roidelapluie** [comment]
Using inspect I notice that the value is e.g. "8000000000.0", so we are probably just not doing the units anymore.

**Comment by brancz** [comment]
Yeah, this is a result of using the columnstore, it doesn't correctly return the unit (yet). I'll keep this open for us to add the unit.

**Comment by brancz** [comment]
Fixed by #990
