### ISSUE TITLE
Validate timestamp of profile

### ISSUE THREAD

**Issue by brancz** [parca-dev/parca#988]
I've noticed that some custom pprof profiles don't set timestamps at all. When that happens we should either use the current times or just reject those profiles.

**Comment by metalmatze** [comment]
I'd be fine with using the current timestamp in that case. Unless we can think of a reason that could be problematic, then I'd simply reject those profiles. Right now, I cannot think of any reason it could be problematic (at least from a Parca perspective).

**Comment by brancz** [comment]
For now, I've added validation in https://github.com/parca-dev/parca/pull/990

It's kind of the same problem as in Prometheus. Letting the target choose the timestamp can be problematic because it requires clocks to be in sync. Having the collector choose the timestamp can mean that the data can't be cached/batched potentially skewing the data.
